### ISSUE TITLE
primary_demand_of_biodiesel should return non-zero result for biomass branch

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#1036]
`V(energy_export_biodiesel, primary_demand)` gives a result of 0.0 locally but returns 53 PJ on BETA.

@antw could you help figure out why this happens? The `energy_production_biodiesel` still is part of the `primary_energy_demand` groups so we are a bit lost as to why the `primary_demand` methods seems to have stopped working for this carrier.

**Comment by antw** [comment]
I have pushed this change to the **[biomass-primary-demand](https://github.com/quintel/etengine/tree/biomass-primary-demand)** branch so that it may be compared with old implementation on the **biomass** branch.

I expect there will be little-to-no fallout as there are no nodes in the graph which are members of the group but which were *not* considered to be at the far-right of the graph for the purposes of the recursive factor calculation. Running `TXT_TABLE(ALL(), key, primary_demand)` shows identical numbers with beta, with the exception of new nodes/edges on the biomass branch.

**Comment by marliekeverweij** [comment]
@redekok and I have compared the new primary demand calculation method with the old primary demand calculation method and we have found no differences in primary demand. We have checked it by comparing the [biomass](https://github.com/quintel/etengine/tree/biomass) ETEngine branch with the [biomass-primary-demand](https://github.com/quintel/etengine/tree/biomass-primary-demand) ETEngine branch and also the [biomass-primary-demand](https://github.com/quintel/etengine/tree/biomass-primary-demand) ETEngine branch with BETA. 

I will now remove `energy_production_corn` and `energy_production_manure` from the `primary_energy_demand`-group, because this is not primary demand statistically. And I will add `energy_production_biogas` to the `primary_energy_demand`-group (there are no losses from corn/manure to biogas, so primary demand will not change, I will check this).

**Comment by antw** [comment]
This change _hasn't_ landed on `master` with the rest of the heat and biomass merge. Let me know if / when you still want to go ahead with this (no hurry).
