### ISSUE TITLE
Hybrid heat boilers in industry show high electricity demand peaks when switching on

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etengine#1118]
A client pointed out that the electricity demand curves for hybrid heat boilers in industry show high electricity demand peaks when switching on. @ChaelKruip and I assume that these peaks compensate for the heat demand that is not produced in the hour before and think that it's modeled like this because of the calculation order of the heat module and electricity merit order but are not sure. @antw , do you know where these peaks come from?

Below you can see the electricity&hydrogen demand and heat output curves for hybrid heat in the chemicals other sector. [This](https://pro.energytransitionmodel.com/saved_scenarios/9257) is the scenario that we've used for the curves.

![P2H industry - electricity and h2 demand](https://user-images.githubusercontent.com/32833996/83882845-f4810e00-a742-11ea-9a8c-4e6fbf25bf3e.png)

![P2H industry - heat output](https://user-images.githubusercontent.com/32833996/83882659-ba177100-a742-11ea-806e-3de61f09a8c0.png)

Notifying @ChaelKruip @AlexanderWirtz

**Comment by antw** [comment]
I'm curious how that **heat output curve** chart was created, because I'm not seeing any values above 2k.

This matches the maximum hourly demand of P2H (the industry_heat profile is flat):

```ruby
MAX(V(
  industry_chemicals_other_flexibility_p2h_hydrogen_electricity,
  heat_output_curve
))
# => 1,947.4564100104262
```

It may be that the spikes are due to refilling the 50MWh buffer; the input capacity of P2H significantly exceeds the hourly demand. If the buffer were empty, it is expected that the electricity load would spike until it is refilled.

There's also chance that the electricity input curve is incorrect. We use a single curve to represent load, rather than separate input and output. This means that if 10 "energy" enters and 10 leaves in the same hour, the net load is 0. In fact the input and output curves should show 10. That might be what's happening here; I'll need to investigate next week.

**Comment by marliekeverweij** [comment]
Thanks @antw for looking into this!!

> I'm curious how that heat output curve chart was created, because I'm not seeing any values above 2k.

I've multiplied the electricity input curve with efficiency of the boiler (99.5%) and multiplied the hydrogen input curve with the efficiency of the hydrogen burner (90%). I see now that I've not take into account the buffer behaviour....

I am not actually understanding what is happening, so I am trying to write what I do understand. The spike occurs because the P2H buffer is not full at that point (hour 154 and 155 in your example), so then more electricity can be converted into heat going into the buffer. When the buffer is full, then electricity is converted into heat that can directly be used in industry (from hour 156 onwards). 
However, actually we would like to model that heat can directly be used in industry in hour 154 and doesn't go to the buffer first, therefore we have modeled the offset of one hour in the heat output curve.

I have a question concerning the heat output capacity and electricity input capacity, how does this work for P2H in industry? In the front-end the heat output capacity of the P2H boiler can be set and in the scenario this is 5945 MW. I would say that this means that the electricity input capacity should then be 5975 MW (= 5945 / 0.995). However, in the scenario the electricity input capacity seems to be 1957 MW (from hour 156 onwards), even though there is enough excess electricity at that moment in the year, see screenshot below (154 hour / 24 = day 6.4).
![Screenshot 2020-06-08 at 10 08 51](https://user-images.githubusercontent.com/32833996/84008587-5a071180-a972-11ea-8f4e-d80f21fd6895.png)

![Screenshot 2020-06-08 at 10 06 58](https://user-images.githubusercontent.com/32833996/84006884-ccc2bd80-a96f-11ea-9f50-fdce6fa955aa.png)

**Comment by antw** [comment]
> I would say that this means that the electricity input capacity should then be 5975 MW (= 5945 / 0.995). However, in the scenario the electricity input capacity seems to be 1957 MW (from hour 156 onwards), even though there is enough excess electricity at that moment in the year, see screenshot below (154 hour / 24 = day 6.4).

I'm not sure where the "1957 MW" is coming from; the capacity of the node says 5975 MW:

```ruby
V(
  industry_chemicals_other_flexibility_p2h_hydrogen_electricity,
  "input_capacity * number_of_units * availability"
)
# => 5974.874371859297
```

... and the curve does indeed peak at this value:

```ruby
MAX(V(industry_chemicals_other_flexibility_p2h_hydrogen_electricity, electricity_input_curve))
# => 5945.0
```

Note that we seem to be compensating the the heat output conversion (99.95%) incorrectly, the peak of the curve should be 5945.0 / 0.995 = 5974.

The technology is often limited to 1957 MW input because this equals the hourly demand on the node:

```ruby
DIVIDE(
  V(industry_chemicals_other_hydrogen_hybrid_heat, demand),
  PRODUCT(MJ_PER_MWH, HOURS_PER_YEAR)
)
# => 1957.2426231115257
```

1957 MWh is subtracted from the buffer, therefore 1957 MW is the maximum electricity load as that will refill the buffer to 100%.

I *do* think that P2H is handling the heat output capacity wrongly: if the heat demand is 1957 MW then the electricity load to refill the buffer *should* be 1966 MW.

**Comment by marliekeverweij** [comment]
👍 

> I'm not sure where the "1957 MW" is coming from

From you example table, the electricity input in hour 156.

> The technology is often limited to 1957 MW input because this equals the hourly demand on the node

Okay, clear, I forgot about the heat demand curve.....  😅 

> I do think that P2H is handling the heat output capacity wrongly: if the heat demand is 1957 MW then the electricity load to refill the buffer should be 1966 MW.

I agree

**Comment by antw** [comment]
@marliekeverweij @ChaelKruip I have a fuller-fix ready for staging, which includes correct accounting of the heat output conversion, but I'm having second thoughts about our earlier decision.

It was agreed that it makes sense for P2H to have a buffer, as heat demand may not always coincide with available excess electricity. However, the demand for heat is constant at 1957 MW. If we limit the P2H input capacity to never exceed demand, then the P2H effectively becomes instantaneous (or rather: is instantaneous with a one-hour delay). Energy that enters the buffer in one hour will always be emitted one hour later, because the constant demand says that it must.

I think our decision may be confusing: if the user says they want 5945 MW input capacity (and a buffer sized to match), should we overrule their decision and limit the P2H to 1967 MW? If a user does not want spikes resulting from a higher input and buffer capacity, why not just lower the P2H capacity slider to the point where no such spikes occur? (1967 MW)?

**Comment by ChaelKruip** [comment]
> I think our decision may be confusing: if the user says they want 5945 MW input capacity (and a buffer sized to match), should we overrule their decision and limit the P2H to 1967 MW? If a user does not want spikes resulting from a higher input and buffer capacity, why not just lower the P2H capacity slider to the point where no such spikes occur? (1967 MW)?

Good point! I tend to agree with you. 

@marliekeverweij @AlexanderWirtz and myself will have a meeting about this tomorrow. We will report back about a way forward if that is okay with you.

**Comment by marliekeverweij** [comment]
I understand your second thoughts.

I think that ideally the max of the P2H output capacity slider is maxed by the heat demand (1967 MW). Users then know that that capacity is used: _what you see is what you get._ However, the slider max can not vary based on other sliders setting (heat technology share %, size of industry, etc.). So I think this is the best way to go! Until we better know how heat buffers in industry really behave (see https://github.com/quintel/etmodel/issues/3368)
