### ISSUE TITLE
Electricity interconnectors with the same hourly price should distribute electricity equally

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etengine#1129]
As mentioned by @ChaelKruip during the interconnectors wrap-up this week: electricity interconnectors with the same hourly price should distribute electricity equally. At the moment the interconnector with a lower number imports/exports electricity first until the max capacity is reached. 

For example interconnector 1 and interconnector 2 both have 35 euro/MWh. At the moment interconnector 1 is first used for import/export and than interconnector 2. However, actually both interconnectors should import/export the same amount of electricity in that hour.

@antw , how much time do you think this will take to implement?

**Comment by antw** [comment]
> @antw, how much time do you think this will take to implement?

I'm not sure. I'm not exactly certain how to implement this yet.

We can assign excesses fairly to industrial P2H because we can assign them all to a [Group](https://github.com/quintel/merit/blob/94992b3cd2119459b998c02e8a854a90c5e5635a/lib/merit/flex/group.rb) and then treat that group as a single merit order participant, with the "share" of each individual P2H known ahead-of-time. This isn't possible for export, since the order of ICs may change in each hour.

If it's not urgent, I'd suggest a "specify" task for a future sprint to try to figure this out.

> For example interconnector 1 and interconnector 2 both have 35 euro/MWh. At the moment interconnector 1 is first used for import/export and than interconnector 2. However, actually both interconnectors should import/export the same amount of electricity in that hour.

Is this true only when exporting excess electricity, or also when using dispatchables?

**Comment by ChaelKruip** [comment]
> Is this true only when exporting excess electricity, or also when using electricity from dispatchables?

Also when using dispatchables.

**Comment by ChaelKruip** [comment]
> If it's not urgent, I'd suggest a "specify" task for a future sprint to try to figure this out.

👍

**Comment by redekok** [comment]
>  electricity interconnectors with the same hourly price should distribute electricity equally

The electricity should be distributed proportionally over the interconnectors based on their capacity, right? For instance, distributing 50MW over two interconnectors with a capacity of respectively 80MW and 20MW results in a distribution of 40MW and 10MW (instead of an "equal" distribution of 25MW and 25MW). Is this also what you meant by distribution electricity "equally" @marliekeverweij?

**Comment by marliekeverweij** [comment]
Yes good point, thanks! That's what I meant
