### ISSUE TITLE
Should primary_demand method use output demand rather than demand?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1147]
The `primary_demand` method uses the _output_ carrier of a node as primary demand carrier. For example, the primary demand carrier associated with `energy_greengas_gasification_dry_biomass` is its output carrier green gas. However, querying the primary demand of that node (`V(energy_greengas_gasification_wet_biomass, primary_demand_of_greengas)`) returns the 'full' demand of the node, not taking into account the output loss. As a result, the ETM returns 1.1 PJ green gas primary demand, although only 0.66 PJ actually comes out of it.

![EnergyTransitionModel - beta-engine energytransitionmodel com 2021-01-13 12-12-31](https://user-images.githubusercontent.com/32056448/104445784-d5304600-5599-11eb-969c-c7547b4a97ff.png)

This makes me wonder whether we should (and could) use the output demand rather than the full/input demand in the primary_demand method? What do you think @ChaelKruip, @antw?

Note that the biomass carriers are a bit odd in the sense that the ETM goes 'beyond' primary demand in modelling the bio 'sources' used to create the primary demand carriers.

**Comment by ChaelKruip** [comment]
> This makes me wonder whether we should (and could) use the output demand rather than the full/input demand in the primary_demand method? What do you think @ChaelKruip, @antw?

It makes sense to do this yes. I'm a bit surprised that it doesn't to be honest!

**Comment by antw** [comment]
I think the explanation for this is fairly simple. There are two versions of the `recursive_factor` method in ETEngine:

* `recursive_factor` – Calculates recursively, compensating for losses along the way.
* `recursive_factor_without_losses` – Calculates recursively, making no adjustments for loss.

Loss compensation means that the recursively calculated value is adjusted so that it includes losses incurred. For example, if we have a primary demand node with three output **carriers**:

* `a` with an output share of 0.5
* `b` with an output share of 0.25
* `c` with an output share of 0.25

```
[ a ]    <-- 0.50 --
[ b ]    <-- 0.25 -- [ primary_demand_node ]
[ loss ] <-- 0.25 --
```

If we were to run `primary_demand(V(a))` we need to include the amount of loss that results from the energy supplied to `a`.

If `primary_demand_node` has demand of 100, the primary demand of `a` is 66.666, *not* 50.0.

* demand of primary_demand_node = **100**
* demand of carrier a = 100 * 0.5 = **50**
* share of loss resulting from a = 0.5 / (0.5 + 0.25) = **0.666**
* loss resulting from a = 100 * (0.25 * 0.666) = **16.666**
* primary demand of a = 50 + 16.66 = 66.666

The biomass node in @michieldenhaan's example has only the greengas and loss carriers, therefore all loss is included in the primary demand.

Assuming this behaviour is undesirable, there are two solutions that I can see:

1. `_of_carrier(...)` methods should *not* use the loss compensation. This would give you the value of the greengas demand, without including losses incurred by the carrier.

   You can try this in your local ETEngine [by changing `primary_demand_of_carrier`](https://github.com/quintel/etengine/blob/36ad683201c6094f3a530a195f812752ab2031fc/app/models/qernel/recursive_factor/primary_demand.rb#L33-L35):

   ```diff
   - demand * recursive_factor(
   -   :primary_demand_factor_of_carrier, nil, nil, carrier_key
   - )
   + demand * recursive_factor_without_losses(
   +   :primary_demand_factor_of_carrier, nil, nil, carrier_key
   + )
   ```

   However, loss compensation affects not only the right-most node in the path (in this case the node in the primary_demand group), but *all* nodes along the path. If you have a path like *a ← b ← c ← primary demand*, and each node has loss, then we compensate for that loss each time. Removing loss compensation from `_of_carrier(...)` might therefore have significant consequences.

   To see why this is so, imagine each of these nodes (*a ← b ← c ← pd*) had 50% loss and the primary demand node has demand of 100. The result of `primary_demand(V(a))` should be 100. If we do not compensate for losses, the primary demand would instead be 100 * 0.5 * 0.5 * 0.5 = 12.5.

   **I'm pretty sure this is not the correct solution**; `recursive_factor_without_losses` is very rarely used.

2. Alternatively, we can change the `_of_carrier` method to only ignore losses on the terminal node which should give you the amount of greengas and nothing else.

   You can try this in your local ETEngine [by changing `primary_demand_factor_of_carrier`](https://github.com/quintel/etengine/blob/36ad683201c6094f3a530a195f812752ab2031fc/app/models/qernel/recursive_factor/primary_demand.rb#L65-L79):

   ```diff
   - factor_for_primary_demand(stop_condition)
   + factor_for_primary_demand(stop_condition) * edge.rgt_output.conversion
   ```

**Comment by michieldenhaan** [comment]
Thanks @antw! Discussed this with @ChaelKruip and the second option is exactly what we're looking for. To double check: Will the 'regular' `primary_demand` method also be adjusted for the output conversion? 
So expected behaviour is:
`V(energy_greengas_gasification_wet_biomass, primary_demand_of_greengas)` = 0.66 PJ
`V(energy_greengas_gasification_wet_biomass, primary_demand)` = also 0.66 PJ

If so, could you put this on the sprint list?

**Comment by antw** [comment]
> `V(energy_greengas_gasification_wet_biomass, primary_demand)` = also 0.66 PJ

This seems odd to me. I understood `primary_demand` to mean the demand of the node – not the demand _minus loss_ of that node – otherwise it's more like the "primary output" than "primary demand".

I think it makes sense to ignore the loss when calculating the primary demand of a carrier, but not so much when getting the primary demand of the node. On the other hand, if we don't subtract the loss from `primary_demand` it won't equal the sum of `primary_demand_of_${each_carrier}`.

I don't have an opinion on which is correct so – if we're sure it's the right thing to do – I'll make it happen.

**Comment by ChaelKruip** [comment]
> otherwise it's more like the "primary output" than "primary demand"

Fair point. I think we might be suffering from a slight but crucial difference in interpretation of what 'primary_demand_of_carrier' should 'mean'.

1. The amount of <carrier> needed for the energy demand of the current node. This interpretation would expect you to recursively traverse the graph (including losses along the way) and return the amount of <carrier> as it *exits* the right-most node where <carrier> can be found.
2. The amount of energy *associated with* <carrier> needed for the energy demand of the current node. This interpretation is identical except at the right-most node where it includes losses of that node (thus returning the input-demand of the right-most node).

@michieldenhaan and myself find interpretation (1) the more intuitive one from a modellers perspective. 

Perhaps we should name the method "primary_output_of_carrier" indeed :)

**Comment by antw** [comment]
> Fair point. I think we might be suffering from a slight but crucial difference in interpretation of what 'primary_demand_of_carrier' should 'mean'.

I actually think we're in agreement: that it *does* make some sense to omit the loss from `primary_demand_of_carrier`.

What I was not-so-certain about is treating the plain `primary_demand` method the same way. However, if you both think that `primary_demand` should also not account for the losses of the primary demand node, then fair enough.

**Comment by ChaelKruip** [comment]
> What I was not-so-certain about is treating the plain primary_demand method the same way.

Good point! I overlooked that one.
I think the behaviour of the 'primary_demand' method will be identical to the 'primary_output' method except for bio-mass carriers for which the method ends at a node which has losses. @antw @michieldenhaan correct me if I'm wrong about this!

Having said that, I'm a bit torn. One the one hand, it would be nice for the 'primary_demand' and 'primary_demand_of_carrier' methods to be consistent. One the other hand, I think it makes sense for the 'primary_demand' method to return a 'demand' indeed (which implies including losses for the end-node).

@michieldenhaan can you weigh in?

**Comment by michieldenhaan** [comment]
I think it is a must that the sum of all carriers of the `primary_demand_of_carrier` method equals the total `primary_demand` method. This basically follows from the definitions of primary demand and primary demand carrier. I think it would be very counter-intuitive if this wasn't the case and it could lead to mistakes in the future.

That said, I think we have two options to ensure this:
- Add new nodes to the graph after the green gas production nodes and put these new nodes in the primary demand group. The input and output of these nodes will just be green gas, no losses. This means that we don't have to adapt the primary demand method but we do end up with 3 fairly boring extra nodes in the graph
- Adapt the primary demand method to skip losses on the terminal node (as discussed).

I have a slight preference for the second option, given that it is probably less effort, avoids extra nodes and is consistent with the _output_ carrier being the primary carrier.

**Comment by ChaelKruip** [comment]
> I have a slight preference for the second option, given that it is probably less effort, avoids extra nodes and is consistent with the output carrier being the primary carrier.

Okay, let's make it happen if you're also fine with it @antw!

**Comment by michieldenhaan** [comment]
To add to this, it seems like `households_solar_pv_solar_radiation` already works as proposed above. I.e. `V(households_solar_pv_solar_radiation, primary_demand_of_electricity)` equals `V(households_solar_pv_solar_radiation, primary_demand)`, neglecting the 83% 'loss' of solar radiation.

**Comment by antw** [comment]
> To add to this, it seems like households_solar_pv_solar_radiation already works as proposed above.

This is because solar radiation is an "infinite" carrier, and nodes with infinite carriers [remove the loss from the share on the primary demand node](https://github.com/quintel/etengine/blob/5d7523dae73c06c3d0782a2aa6623adfbc39376f/app/models/qernel/recursive_factor/primary_demand.rb#L92-L95). I can't tell you why, as this is another case of the code predating the ETEngine commit history.
