### ISSUE TITLE
Inconsistent demand and output of wind electrolysis

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1174]
Scenario: 835873 (PRO)

Graph shows an input of 81 PJ, demand of 76 PJ and hydrogen output of 53.5 PJ. So 5 PJ disappears from input to demand. Also output efficiency is 66%. 76 * 0.66 = 50.2 PJ hydrogen output, not 53.5 PJ. Querying `V(energy_hydrogen_electrolysis_wind_electricity,output_of_hydrogen)` also returns 50.2 PJ hydrogen output but graph uses 53.5 PJ.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/32056448/118945119-728af480-b955-11eb-8fe4-381ca4d5253b.png">

**Comment by antw** [comment]
I'm pretty certain this is happening because in Reconciliation (hourly H2) the implementation [limits the hourly demand by the capacity of the electrolyser](https://github.com/quintel/etengine/blob/23e861ad85b51ff507b605ed120b339f04c6468d/app/models/qernel/reconciliation/electrolyser_adapter.rb#L37-L45). This is the defining feature of the custom electrolyser behaviour.

In https://github.com/quintel/etengine/commit/2d5733f3a55369397c8601ae47408ae939c4d194, Reconciliation was changed so that it would run _after_ the second graph calculation. This was in response to https://github.com/quintel/etmodel/issues/3354; with which I haven't yet re-familiarised myself.

This quite obviously (in hindsight, anyway) causes problems when the electrolyser then changes demands and shares on the graph. Instead of those changes propagating through the graph – as they would have when Reconciliation took place _before_ the second graph calculation – the graph ends up in an inconsistent state.

I'll have to revisit that issue from a year ago and see if there is an alternative solution.
