### ISSUE TITLE
API delivers inconsistent results on get /inputs

### ISSUE THREAD

**Issue by thesethtruth** [quintel/etengine#1183]
Hi guys,

First of all, thanks for all the work you've done on the ETM. I'm currently using it for my master thesis on systems integration optimization for a high share of VRE in the RES's of Gelderland. 

While working with the API for a parametric experiment I noticed that I got some unexpected behavior when requesting all inputs. The API documentation states the following: 

> "To get an overview of all the inputs available in the ETM, complete with their minimum, maximum, and default values and unit, one should make the following request:"
> $ curl -i https://engine.energytransitionmodel.com/api/v3/inputs

However, I've found that I get inconsistent values returned. To test this I wrote a simple loop to compare the returned default values of two variables (# inhabitants and share of cars in transport) with a 5 min pause between the calls. Below you can find the results.

|    |   households_number_of_inhabitants |   transport_cars_share |
|:---|-----------------------------------:|-----------------------:|
| t0 |                           0.022716 |                79.6991 |
| t1 |                           0.022    |                79.6991 |
| t2 |                           0.022    |                79.6991 |
| t3 |                          16.9007   |                73.5826 |
| t4 |                           0.022    |                79.6991 |
| t5 |                           0.046    |                74.3752 |
| t6 |                           0.046    |                74.3752 |
| t7 |                           0.046    |                74.3752 |
| t8 |                           0.046    |                74.3752 |
| t9 |                           0.046    |                74.3752 |

If this is expected behavior (and I'm missing the pattern) or I'm using the API incorrectly, please let me know. But as far as I can tell only 't3' returns the expected value. Which would be the default for the Netherlands in 2018. 

I'd like to add that this same issue seems to be present when using a request session object. I've crosschecked with various scenarios on the "GET /scenarios/:scenario_id/inputs" endpoint and have not been able to find any anomalies. 

Kind regards,

Seth

---

The code I've used:
```
# consistency-check.py
from time import sleep
import requests

burl = "https://engine.energytransitionmodel.com/api/v3"
inputs = "/inputs"
test_variable1 = "households_number_of_inhabitants"
test_variable2 = "transport_cars_share"
rest = 60*5 # 5 min pause between calls

results = dict()
for i in range(10):
    r = requests.get(burl + inputs)
    d = r.json()
    tv1 = d[test_variable1]["default"]
    tv2 = d[test_variable2]["default"]

    results.update({f't{i}': {test_variable1: tv1, test_variable2: tv2}})
    sleep(180)
```

**Comment by noracato** [comment]
Hi Seth,

Thanks for your question and detailed explanation. We are currently busy updating and moving our API documentation to our new [official documentation website](https://docs.energytransitionmodel.com/api/intro). The `/inputs` endpoint you are speaking about will not survive that transition.

The `/inputs` endpoint works the same as `/scenarios/:id/inputs`: it uses a scenario to return the inputs from. For the `/scenarios/:id/inputs` it's clear what scenario is used (the one supplied by the id). In the case of the `/inputs` endpoint however, this is the _most recently_ created scenario in the ETM. As many scenarios are created in the ETM daily, the most recently created scenario can have area `nl2018`, but can also be about a municipality, a region or a whole other country. 

In your example we see that in the span of 50 minutes about 4 scenarios have been created by ETM users. One of which was a scenario of the Netherlands.

Because of the unpredictability of the `/inputs` endpoint we discourage it's use, and will remove it in the future in favour of something more stable.

Sorry if it caused you any troubles, and thanks for alerting us! Feel free to ask any questions if I wasn't clear.

Cheers,
Nora

**Comment by thesethtruth** [comment]
Hi Nora,

Thanks for your swift reply! That clears things up. Great to hear that you are working on new documentation of the API, as it is a bit sparse in some regards ;) 

Lacking a contradiction I had assumed that the default would be the same scenario as you would using the GUI on pro etmodel.

For future use, I will include the default area code `nl2018` to obtain the values I was expecting. 

Cheers!
