### ISSUE TITLE
Mismatch in primary demand of energy_chp_local_engine_biogas

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1184]
As discussed briefly in https://github.com/quintel/etengine/pull/1182, scenarios with a positive demand for `energy_chp_local_engine_biogas` have a mismatch in total primary demand vs. primary demand of final demand and exports.

E.g. scenario 1453631 with a lot of biogas CHP capacity. 
```
SUM(V(G(primary_energy_demand),primary_demand)) - 
SUM(V(G(final_demand_group),G(energy_export), energy_flexibility_curtailment_electricity, industry_locally_available_refinery_gas_for_chemical, primary_demand))
```
should return zero, but instead returns 59,760,609.67 MJ. This means that either total primary demand is overestimated or some primary demand goes missing when looking at the final demand and export nodes. When removing the biogas CHP from the scenario, the mismatch drops to 1 MJ.

One possible lead: The biogas CHP is special because it is the only CHP that is must-run. All other CHPs are dispatchable. I presume that this is thus also the only CHP for which heat production is available immediately, instead of shifted one hour as for the dispatchable CHPs (is this correct @antw?). The biogas CHP has a flat profile with an hourly heat production of 53,147,881 MJ. This is quite close to the mismatch, especially when taking into account that the mismatch is about _primary demand_, not heat production (the primary demand of the heat production is higher than the production itself due to conversion losses). So maybe it has to do with over/underestimating heat production in the final hour?

Assigning @antw, let me know if I can help! This is not super urgent but would be nice to fix at some point in time.

**Comment by antw** [comment]
> this is thus also the only CHP for which heat production is available immediately, instead of shifted one hour as for the dispatchable CHPs (is this correct @antw?)

It should have the same one-hour delay as any other Merit-reliant heat producer. You're right that the delay isn't *necessary* for this participant since the electricity part is "must-run". The easiest way to remove the delay is to change the heat network part to use the same profile as the electricity part:

```diff
- - heat_network.group = self: electricity_output_curve
+ - heat_network.group = flat
```

I've done this on the ETSource master branch and the mismatch disappeared almost entirely:

```ruby
SUM(V(G(primary_energy_demand),primary_demand)) - 
SUM(V(G(final_demand_group),G(energy_export), energy_flexibility_curtailment_electricity, industry_locally_available_refinery_gas_for_chemical, primary_demand))
# => 0.64453125
```

Ideally, ETEngine would do the right thing automatically, but as the biogas CHP is the only affected heat network participant I feel it's okay to just change the profile. Let me know please if you disagree.

**Comment by michieldenhaan** [comment]
Very nice, thanks! 🙏
