### ISSUE TITLE
Electricity price should only be zero when all demand is satisfied

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1205]
Scenario II3050 National

I noticed quite a few hours with an electricity price of 0. The scenario has 50 GW of P2G installed, willing to pay 30 euro/MWh. I would expect the electricity price only to go to 0 when all demand (inflexible + flexible) is fully satisfied. Otherwise, we wouldn't be in an equilibrium point. E.g. in the hour halfway 5 and 6 January the price is 0, yet almost no flex demand is utilised in that hour. For a price of 0, 50 GW of demand from the P2G would be willing to run. So a price of 0 would not occur, unless all technologies willing to pay > 0 are running at full capacity.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/32056448/142050321-c1c1223e-12ea-45b7-88c0-62ca24b6b6d3.png">

It looks like it's unrelated to https://github.com/quintel/etengine/issues/1204 as this also happens when reverting the last few commits.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/32056448/142051424-d619c093-a77f-4def-8289-e382a313e862.png">

**Comment by michieldenhaan** [comment]
Thanks @antw. I assumed this was communicated to you at the start of the project, but the plan was indeed to remove the "use of dispatchables for export" toggle and assume it is always on. Sorry for the confusion. In the current modelling, we have two types of export: export of excess electricity and export from dispatchables. In the new modelling, the first one should be removed, export only takes place when it's willingness to pay is high enough and can be served both by must-runs and dispatchables. 

Hopefully this makes things a lot easier: export should not be special in any way but simply be another flexible consumer with a capacity (interconnector capacity) and willingness-to-pay (fixed price or hourly price curve)

**Comment by antw** [comment]
> I assumed this was communicated to you at the start of the project, but the plan was indeed to remove the "use of dispatchables for export" toggle and assume it is always on.

Wasn't aware of that, but it certainly does make matters easier.

As of quintel/etengine@ebc3752a (price-sensitive-flex branch) this should be fixed whenever export is allowed to consume from dispatchables:

![Electricity price per hour 1494999](https://user-images.githubusercontent.com/4383/142245357-1801e514-c4bd-45e3-a656-dab56c2c7df1.png)

This is still not _quite_ perfect: there is one hour on the 3rd of January where the MV battery becomes price-setting when discharging. This is because the MV battery has no `marginal_costs` attribute yet, so it defaults to 0.

[I mistakenly added sample attributes for household batteries](https://github.com/quintel/etsource/blob/ba74579bc7314c75a2201e03c208c974d354785f/graphs/energy/nodes/households/households_flexibility_p2p_electricity.converter.ad#L20-L21) when adding this feature. All batteries will need real values, after which I think the price curve will behave as expected:

* energy_flexibility_hv_opac_electricity
* energy_flexibility_mv_batteries_electricity
* energy_flexibility_pumped_storage_electricity
* households_flexibility_p2p_electricity
* transport_car_flexibility_p2p_electricity

**Comment by michieldenhaan** [comment]
> this should be fixed whenever export is allowed to consume from dispatchables

Thanks a lot 🎉! For the record: We plan to remove the toggle from the interface. Is it possible to 'enable' this export-from-dispatchable behaviour by default (and in fact no longer offer the option to not have this)?

> I mistakenly added sample attributes for household batteries when adding this feature. All batteries will need real values, after which I think the price curve will behave as expected

I've added dummy values to all batteries now on the branch. Willingness-to-pay of 0.50 Eur/MWh and marginal costs of 1. Still I find it difficult to interpret the results, e.g. the same scenario with the export toggle on:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/32056448/142256984-16cf1809-fc0f-4263-9f45-18b1193ec6ab.png">

There is battery charge in the first few hours, even though their willingness to pay is 1 Eur and we have 50 GW of power-to-gas willing to pay 30 euro. So I would expect batteries to only start charging once the full 50 GW of power-to-gas is deployed

Also when adding 60 GW of power-to-heat boilers with a willingness to pay of 19 Eur/MWh, the electricity price comes close to 0 in a few hours. However, with 50 GW power-to-gas willing to pay 30 euro and 60 GW power-to-heat willing to pay 19 euro, I would expect the electricity price only to go below 19 Eur/MWh when the residual load curve is at least 110 GW below zero.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/32056448/142257300-22f601ef-1899-4c88-b2a5-465c89ab8a8a.png">

**Comment by antw** [comment]
Thanks for continuing to test this @michieldenhaan. I've pushed some changes to ETEngine/Merit which I believe fix these issues:

![Flexible electricity demand and supply per hour 1494999](https://user-images.githubusercontent.com/4383/142624843-103032b7-ddcd-4401-8399-a2aae8b8e093.png)
![Electricity price per hour 1494999](https://user-images.githubusercontent.com/4383/142624860-f6467fba-6f54-4c7b-b0e9-b1241f81228d.png)

**Comment by michieldenhaan** [comment]
Thanks! Two things still seem counterintuitive:

- In some hours in the red circle there's exports, but the interconnector price in that hour seems to be below 30 EUR/MWh. So I would expect the P2G to be prioritized over exports
- Later on (also in the red circle) the price seems to drop below 30 EUR/MWh, tho there is little to no P2G running in that hour. Given that P2G is willing to pay 30 EUR/MWh, the price should only drop below 30 EUR when P2G is running at full capacity (51 GW).

![image](https://user-images.githubusercontent.com/32056448/142632150-13a40864-8a2a-41c7-ba4f-e6bb5f3a974d.png)

**Comment by antw** [comment]
🤞

![Flexible electricity demand and supply per hour 1494999](https://user-images.githubusercontent.com/4383/142661185-70b006e4-6b43-461f-94b7-6f92b793e11b.png)

![Electricity price per hour 1494999](https://user-images.githubusercontent.com/4383/142661194-79851cf3-2f71-426e-810b-1f43f3cae8e6.png)

The price drops to €1 for one hour on 3rd of January when the MV battery discharges to meet baseload demand and is the marginal producer. P2G does not kick in for that hour because batteries are currently disallowed from discharging when the consumer is another flexible technology.

**Comment by michieldenhaan** [comment]
Nice!

> P2G does not kick in for that hour because batteries are currently disallowed from discharging when the consumer is another flexible technology.

Is it possible to allow this? When discharging, the battery should be like any other dispatchable (flex supply) technology, so discharging for P2G is fine. Similarly, when charging the battery should be like any other flex demand technology, so running dispatchables to charge the battery is fine (given that willingness to pay > marginal cost)

**Comment by antw** [comment]
> > batteries are currently disallowed from discharging when the consumer is another flexible technology.
>
> Is it possible to allow this?

Yes! In fact, it's only two lines of code that currently prevent batteries from supplying other flexible technologies.

However, batteries then become very dependent on setting sensible charge and discharge prices, otherwise they behave (IMO) counterintuitively.

For example, in the above scenario, there are MV batteries installed that use the default prices from ETSource:

* Discharge for any consumer willing to pay €1 or more
* Charge whenever the electricity price is €25 or less

![Flexible electricity demand and supply per hour 1494999 (1)](https://user-images.githubusercontent.com/4383/142859083-92f678b6-df8e-4fad-bf83-c14b6313403d.png)

The battery charges (pink) using excess electricity until it's full. In hours when charging, it is not allowed to discharge. The battery is willing to pay €25 for electricity while P2H will pay only €22; therefore the battery has priority. When the battery is full and can no longer charge, it becomes free to discharge, which it does for one hour into P2H (yellow) for €1.

This problem goes away when the battery discharge price (marginal cost) is set to €26 presumably because P2H is no longer willing to pay this price.

![Flexible electricity demand and supply per hour 1494999 (2)](https://user-images.githubusercontent.com/4383/142859110-326ced11-6588-462b-b013-ac9613efc82e.png)

I think the problem can be simplified as "when the battery discharge price (marginal cost) is lower than the charge price (max consumption price), and another flex technology sits between those two prices, batteries will behave strangely".

**Comment by michieldenhaan** [comment]
🎉 awesome!

> I think the problem can be simplified as "when the battery discharge price (marginal cost) is lower than the charge price (max consumption price), and another flex technology sits between those two prices, batteries will behave strangely".

One thing we could consider is to ask the user to set the discharge price as a _mark up_ on the charge price, rather than setting an absolute price. This would prevent users setting a higher charge price than the discharge price. What's your opinion on this @mabijkerk, @ChaelKruip?

**Comment by michieldenhaan** [comment]
Thanks for the fixes @antw!

One small request: Could you make sure 'export from dispatchables' is always 'on'? I've removed the input/toggle from ETSource/ETmodel. 'On' maybe isn't the right word here because there no longer is an 'off' 😄 

Another thing I noticed:

I've added 22.4 GW of heat pumps to the II3050 National scenario. These heat pumps have a COP of 4.5 so the total installed electrical input capacity is around 5 GW. In other words, 5 GW of flexible electricity demand. On 14 January electricity is curtailed at some point. However, the heat pump isn't running at 5 GW at that moment.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/32056448/143222868-8084e376-de36-40e7-b70f-6a360403282f.png">

I think it's around hour 347. The electricity input curve shows 1.2 GW at that time:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/32056448/143223441-337b13ee-a9e4-47d2-8aea-fb111250c8e8.png">

Later on in the year (hour 2984) the input capacity reaches 4.7 GW. Can you see why curtailment kicks in without the heat pump running at full capacity?

**Comment by michieldenhaan** [comment]
It looks like the issue disappears when battery charge has a lower WTP than power-to-heat (I updated the default WTP of batteries from 20 to 4 euro/MWh after creating this issue).

Steps to reproduce:
1. Open II3050 National
2. Install 22400 MW P2H Heat pumps
3. Change WTP of batteries to 20 eur/MWh for all batteries
4. Change WTA of batteries to 30 eur/MWh for all batteries

This should give the results I referred to in my previous comment

**Comment by antw** [comment]
Thank goodness for your keen eye @michieldenhaan :pray:

[It was indeed a bug](https://github.com/quintel/merit/commit/a3afcc4b5c490e3981f593605c4a182d69fec784).

![Flexible electricity demand and supply per hour 1495016 (3)](https://user-images.githubusercontent.com/4383/143276083-e6f9ca73-3238-484c-8e0c-0af0f5717373.png)

P2H is grouped with MV batteries due to them having the same price, and excess energy is assigned proportionally to the capacity of each technology. The batteries, having much greater capacity than P2H (25GW vs 5.4GW), get much more of the excess with P2H getting to run at full capacity once the batteries are full on the 10th Jan.

**Comment by mabijkerk** [comment]
> One thing we could consider is to ask the user to set the discharge price as a mark up on the charge price

I think this is a good idea. I don't think we want users to be able to set their discharge price below their charge price, as it will probably lead to undesirable behaviour.

**Comment by ChaelKruip** [comment]
What is the status of this?
