### ISSUE TITLE
Higher WTP than WTA produces wrong results for P2P

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1215]
I am testing the mechanical turk [flexibility_spec.rb](https://github.com/quintel/mechanical_turk/blob/master/spec/flexibility/flexibility_spec.rb) on BETA. When I open a blank scenario, add 30000 MW of inland wind turbines, set the share of household batteries to 100% and their WTP on 45.0 euro/MWh I get [this scenario](https://beta-pro.energytransitionmodel.com/saved_scenarios/4999).

The WTA of household batteries in a blank scenario is 4.4 euro/MWh. **Without** the batteries installed the hourly price curve looks like this:
<img width="500" alt="Screenshot 2021-12-23 at 14 57 01" src="https://user-images.githubusercontent.com/67338510/147250313-8498ee65-35d9-4905-9f3f-6c69b6956983.png">

In the first few hours of this series, where the price is around 38 euro/MWh, I'm not sure what the batteries should do. In principle they would be willing to discharge, because the price is higher than their WTA, they would also be willing to charge, because the price is lower than their WTP. @antw do know you what the intended behaviour is, should they be indifferent to charging/discharging? I think it also relates to this discussion: https://github.com/quintel/etengine/issues/1205#issuecomment-975514394.

Once the batteries are added, the model produces very strange results. The electricity output curve of `households_flexibility_p2p_electricity` is 0 throughout the year, meaning that there is no discharge, but the battery does keep on charging even though the SOC is at 100%:
<img width="500" alt="Screenshot 2021-12-23 at 15 11 27" src="https://user-images.githubusercontent.com/67338510/147251926-2b3cf94b-e02e-4e3c-b8e2-51f2b41e9e1e.png">

From the start of the series the volume is at 78 GWh, which is the storage volume of the household batteries, showing that the SOC is 100%:
<img width="500" alt="Screenshot 2021-12-23 at 15 11 56" src="https://user-images.githubusercontent.com/67338510/147251976-c272e19c-0324-452f-828a-8e4f1d2c8ab0.png">

If we cannot come up with sensible behaviour for P2P when their WTP > WTA, then we might have to resort to having a markup.

**Comment by antw** [comment]
There is a bug here; the battery is charging and discharging in the same hour when it shouldn't be allowed to do that. I've fixed it locally, but that just reveals how silly it is to have a lower willingness to accept than to buy:

![Screenshot 2021-12-24 at 15 30 42](https://user-images.githubusercontent.com/4383/147362290-eaee47d9-c10e-4393-8d05-a917c2d4f2cf.png)

If the battery has any energy stored it will prefer selling to buying, and as soon as it is empty it will again be willing to buy. The result is that the battery oscillates between charging and discharging. Obviously, this is not good. 😅

Ideally, we might link the "pay" and "accept" sliders so that accept will "always" be at least "pay" and "pay" will be no higher than "accept", but I fear this is quite complex:

- We don't currently support linked sliders.
- I'm not sure how we'd handle this in ETSource and ETEngine, since the min/max values of input would be dependent on another (currently they are fixed, per dataset).
- It's not clear to me how this could be made obvious to API users.

I don't love the idea of a "mark up" slider since it doesn't feel as intuitive, but I'm not sure what else to suggest.

**Comment by mabijkerk** [comment]
> There is a bug here; the battery is charging and discharging in the same hour when it shouldn't be allowed to do that. I've fixed it locally

Great! Could you push that fix?

> The result is that the battery oscillates between charging and discharging.

This behaviour is logical given the input parameters, but it does not lead to results that are useful either for the energy system or for the battery itself. The **benefit** of keeping it as is, is that the user will be able to see that it does not lead to useful results. The **downside** is that the user might not understand the behaviour and disengage from trying the flexibility section.

I'm not necessarily against a mark-up slider: a percentage markup would make it easy to set it to the inverse of the roundtrip efficiency losses. Let's first see what comes up in during testing and then decide whether it's worth changing.
