### ISSUE TITLE
Design connection refinery sector

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etengine#1220]

**Comment by mabijkerk** [comment]
We made the following design direction for the refinery sector:

<img width="1584" alt="Screenshot 2022-01-20 at 14 07 41" src="https://user-images.githubusercontent.com/67338510/150344692-bdccae8f-de55-4baa-bf5f-ecc6abca10a3.png">

**Energetic demand**
- Allow the API input statements to affect the `industry_useful_demand_for_chemical_refineries_useable_heat` node for all the energetic demands with the exception of electricity.
- The demand for electricity is set in a separate input statement for the `industry_useful_demand_for_chemical_refineries_electricity` node.
- **Challenge:** use of hybrid heaters will lead to demand for electricity (and reduced demand for network gas or hydrogen) that is hard to determine in advance in the CTM. Question is therefore how to deal with these heaters.

**Non-energetic demand**
- Allow the API input statements to affect the `industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic` node.
- The outputs of the refinery transformation can then be changed in the `industry_refinery_transformation_crude_oil` node.
- This has a somewhat lower priority since the bandwidth for changes is not that large.
- **Challenge:** the refinery transformation node produces refinery gas, which is used as an energetic input in the refinery itself. Doing so in the graph would lead to a circular reference, which would break the graph. This is why the node `industry_locally_available_refinery_gas_for_chemical` is an endpoint in the graph. The demand for refinery gas is modelled as additional energetic crude oil demand, which is problematic since the carbon content of crude oil differs from refinery gas.
- This challenge cannot be solved within this project.
- In addition to the non energetic crude oil demand, we may want to set non energetic demand for different carriers.

**Comment by mabijkerk** [comment]
See comment https://github.com/quintel/etengine/issues/1222#issuecomment-1017513622:

> The graph is calculated left-to-right except when nodes are connected by reversed edges.

Therefore the approach described above seems viable.

**Comment by mabijkerk** [comment]
After discussion with Kalavasta:

- All the carriers that they have as output in the model seem to be present already in the ETM

Based on this I think we can start working on the approach outlined above.
