### ISSUE TITLE
Add support for scenario metadata

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1223]
Connecting the ETM with the CTM requires that we store the CTM scenario ID with the ETEngine scenario. Integration with other models in the future may require that we add yet more attributes.

I think we have two options:

1. Add a `ctm_scenario_id` attribute to scenarios that would allow an API user to set the numerical ID of the CTM scenario.
2. Add a `metadata` attribute to scenarios. This would be a JSON object which can be structured however the API user chooses. A freeform "metadata" field might be useful to other users of the API.

I personally lean in favour of the second option, since it means that integration with other models could also use this attribute to store anything of relevance.

However, we'd need to consider what we do when a scenario is cloned. This happens regularly when users create new scenarios through the API and when ETModel creates new saved scenarios., or starts a new scenario based on a saved scenario. Should we also clone the CTM ID / metadata? My gut feeling is that cloned scenarios shouldn't link back to the CTM anymore, but I'm not sure about this. We might need to seek the advice of Kalavasta.

Whichever option is decided, we need to:

* Add the field in ETEngine.
* Update the API to accept this field.
* Validate data provided by the user (if option 1: validate that is a number; if option 2: perhaps validate that they aren't trying to store an excessive amount of data).
* Update the API documentation.

**Comment by marliekeverweij** [comment]
@antw @noracato during the client meeting this morning we heard that the CTM scenario database is not created yet; they expect it to be ready by the end of January. Is that a problem for the implementation of this todo?

Notifying @ChaelKruip

**Comment by noracato** [comment]
Thanks for the clear write up @antw! I went with the metadata idea, because that seemed to me the most future-friendly format.

While working on this, I came about some topics I'd like your opinion on:

1. How much do we touch the metadata object, and how much do we leave up to the user to decide / do we not care about? As this object is mostly for a users 'own' information, they should have a decent amount of control over it, and we should not care _that_ much. Does that mean:
   - That we should make the metadata nicely accesible throughout the engine by e.g. converting keys to symbols, and numeric strings to floats and ints? Or just leave it bare?
   - That we should always merge updated metadata in with the existing metadata, or let users overwrite the whole object?
2. When to show the metadata. My thought was to only add this information when the`detailed` parameter is set to true in API calls.
3. I put the metadata limit on 2000 characters, is that a fair amount? And would we need more protection than that?
