### ISSUE TITLE
Sum of input statements in a group should be checked to sum to 100%

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1232]
During testing of the input statements in the ETM-CTM through the 'edit scenario' feature of ETEngine the following came up:

When setting the input or output shares of a certain node, for example the output shares of `industry_refinery_transformation_crude_oil`, it is possible to choose the shares in such a way that the total sum does not match 100%. In the example below you can see that the sum equals 110%:

<img width="1348" alt="Screenshot 2022-02-10 at 11 11 40" src="https://user-images.githubusercontent.com/67338510/153385525-f3382938-ae28-43c2-a67a-938286d69ecc.png">

This results in energy being 'created' from nothing, showing in the node demands as a higher output demand than the input demand:

<img width="800" alt="Screenshot 2022-02-10 at 11 12 36" src="https://user-images.githubusercontent.com/67338510/153385648-65acfc4b-d700-43d4-b2a7-e1fe28228a4d.png">

@antw is there a way to check whether the input and output shares of a certain node that is changed by input statements sum to a 100%? As far as I know, in the ETM front-end the shares are automatically adapted. However, this may not be the most useful solution here. For example, when you have just updated the kerosene output share in the node above, you wouldn't want the next input statement to readjust the kerosene output share.

Notifying @marliekeverweij

**Comment by antw** [comment]
The scenario editor page needs a revamp at some point because, as you have noticed, we don't do any validation on the values entered in that form. We also need to do a better job of representing the "balanced values": inputs set automatically by ETEngine to ensure a group sums to 100%. We could also do with an editor for the new metadata field, and some way of showing uploaded files (especially custom curves).

However, API users don't need to worry about this. They either opt into the auto-balancing behaviour, or are themselves responsible for ensuring their groups sum to 100%. If they choose the latter, we reject any update containing a group that doesn't sum to 100%, returning an error instead.

**Comment by mabijkerk** [comment]
Thanks for the insight. It is good to know that this issue can only occur in the scenario editor. Because is it not an issue for the connection of external models through the API, I will will close this issue.
