### ISSUE TITLE
create new scenario form doesn't submit

### ISSUE THREAD

**Issue by twilkinson573** [quintel/etengine#764]
Doesn't submit in production or staging due to a routing error

![image](https://cloud.githubusercontent.com/assets/6432221/6328933/589eea88-bb6c-11e4-86ec-df5a0a01dba9.png)

**Comment by antw** [comment]
There's no action in the [Data::ScenariosController](https://github.com/quintel/etengine/blob/master/app/controllers/data/scenarios_controller.rb) either.

/faceplam

How urgently is this needed? I'm pressed for time on another project, and this isn't entirely straightforward because we need to account for share groups (ensuring that grouped of sliders sum to 100%) when creating your scenarios.

**Comment by twilkinson573** [comment]
Haha that does make it interesting!

@jorisberkhout what do you think?

I don't mind biting the bullet and entering the scenarios if there's a less elegant, more 'manual' way

**Comment by jorisberkhout** [comment]
I would like to have the scenarios today, but am willing to spend time on the 'manual' way if you are pressed for time, @antw. The share groups should be no issue in this case, as I checked those in the original Excel document.

Would it be possible to fix only the first part of the issue today (and trust me on the share groups), @antw. If not, I will find some help and enter the scenarios manually.

**Comment by antw** [comment]
> I would like to have the scenarios today [...] The share groups should be no issue in this case, as I checked those in the original Excel document.

That makes things simpler; I'll do this now. I'll make a second pass at a later date to account for share groups.

**Comment by jorisberkhout** [comment]
Thanks a lot, @antw! You saved my day :smile: :

**Comment by antw** [comment]
Pushed, and should be on staging momentarily. It's had minimal manual testing, but it appears to work. :pray:
