### ISSUE TITLE
Question: why do these input statements work?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#776]
There are a couple of incidents lately where I look at an input statement and do not understand how it could work. Perhaps we can learn something about these mysterious beings by asking the right questions... I was hoping that @antw could help me on my quest.
## Climate slider

In [this input statement](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_climate/households_climate_influence.ad), the user input is used to calculate an update percentage for heating and cooling. Let's look at the cooling one:

```
x = USER_INPUT();
    cool_factor = 56.69449 * x + 1598.105 * x**2 + 25375.5 * x**3 + 163210.71413778 * x**4;
```

User input is between -5 and +5. When constructing this input, I found out that x is actually interpreted by etengine as if it would lie between -0.05 and +0.05. Therefore, I had to multiply the first term in the above equation by 100, the second by 100^2 = 10000 etc. in order to end up with a factor that would represent the actual multiplication factor for the cooling demand. I don't understand how this can be...
## households_water_heater_heatpump_air_water_electricity_share

[This input](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_hot_water/households_water_heater_heatpump_air_water_electricity_share.ad) was [recently fixed](https://github.com/quintel/etsource/commit/31c4c67dbb4a4159ac21b647b56a976527cdea43) because it suddenly started to fail in the Mechanical Turk tests. I don't understand why...
## households_water_heater_network_gas_share

[This input](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_hot_water/households_water_heater_network_gas_share.ad) has an update statement that only contains the following code:

```
EACH()
```

I think that is highly suspect but apparently it has been working like this forever. Perhaps it is because the slider is part of a slider group and the others take care of balancing somehow?

Including @dennisschoenmakers @jorisberkhout

**Comment by antw** [comment]
> Climate slider
>
> User input is between -5 and +5. When constructing this input, I found out that x is actually interpreted by etengine as if it would lie between -0.05 and +0.05.

The `update_type` attribute is set to `%`. This will cause the `USER_INPUT()` to be [divided by 100](https://github.com/quintel/etengine/blob/90af3cf3a6405e3fe08d088cd4a3ffe83480254a/app/models/gql/runtime/functions/update.rb#L165-L173) to convert it to a factor. If you want the original value (between -5 and 5), remove the `update_type` attribute.

> households_water_heater_network_gas_share
> 
> I think that is highly suspect but apparently it has been working like this forever. Perhaps it is because the slider is part of a slider group and the others take care of balancing somehow?

You're right, the empty `EACH()` does nothing. I tested it manually (by editing values in the database so as to ignore the rest of the group) and can confirm that input statement does not set any value. *It does not need to do so*, however, since the network gas edge [is `type=flexible`](http://beta.et-engine.com/data/417124/converters/households_useful_demand_for_hot_water_after_solar_heater_and_p2h). I'm reasonably certain you could remove the `EACH()` (and probably the entire `- query = ...` line) without any ill effects.

> households_water_heater_heatpump_air_water_electricity_share
>
> This input was recently fixed because it suddenly started to fail in the Mechanical Turk tests. I don't understand why...

Not sure about this one. Will investigate.

**Comment by ChaelKruip** [comment]
@antw thanks for clarifying!
