### ISSUE TITLE
The 'demand_of' method does not work on some nodes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#786]
This is a weird one. The 'final_demand_of_<carrier>' method returns 0.0 for several nodes in the `final_demand_group` although they have a demand and it is properly calculated by the 'demand' method.

The nodes are:

* energy_power_sector_own_use_electricity
* energy_cokesoven_consumption_coal_gas
* energy_export_coal_gas
* energy_heat_network_unused_steam_hot_water

which are indeed 'odd ones out' in the sense that they don't have `final_demand` in their names. More importantly (possibly): they don't have any children (no connections on the left).

The [code where the final_demand_of is calculated](https://github.com/quintel/etengine/blob/master/app/models/qernel/recursive_factor/final_demand.rb#L10-L15) makes use of the recursive factor. Perhaps the recursive factor has trouble with nodes that are end-points (when going from right to left)?

Including @dennisschoenmakers @AlexanderWirtz @jorisberkhout

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @AlexanderWirtz @jorisberkhout

**Comment by ChaelKruip** [comment]
Changed milestone to coming deploy because it would be nice if we could update the renewability chart.

@antw can you please make an estimate how complex this is to fix?

**Comment by antw** [comment]
@ChaelKruip Can you provide one or two GQL statements which you would expect to be non-zero? I'll take a quick look into this today.

**Comment by ChaelKruip** [comment]
```
V(energy_export_coal_gas, demand_of_coal_gas)
```
should give the same as 
```
V(energy_export_coal_gas, demand) = 27,135,045,383.07142
```
 but returns 0.0.

**Comment by ChaelKruip** [comment]
Same story for `V(energy_power_sector_own_use_electricity, demand_of_electricity)`

**Comment by antw** [comment]
Thanks for that. I'm a bit confused because the title and examples make mention of `demand_of`, but the issue description says `final_demand_of`.

`demand_of` doesn't use recursive factor, and simply returns the amount of energy which *leaves* the converter as a particular carrier. [It's an alias of "output_of_carrier"](https://github.com/quintel/etengine/blob/a61000ef3add0ae903ecc4666bab89168be33f35/app/models/qernel/converter_api.rb#L180-L182). `demand_of_coal_gas` is asking for the amount of energy which is *output* by the converter to the left. As `energy_export_coal_gas` does not have a coal_gas output, this returns zero.

If you wanted to query the amount of energy which enters the converter (from the `energy_distribution_coal_gas` on the right), you should run `supply_of_coal_gas`.

```ruby
EACH(
  V(energy_export_coal_gas, demand),              # => 27,135,045,383.07142,
  V(energy_export_coal_gas, supply_of_coal_gas),  # => 27,135,045,383.07142
  V(energy_export_coal_gas, demand_of_coal_gas)   # => 0.0
)
```

**Comment by ChaelKruip** [comment]
> I'm a bit confused because the title and examples make mention of `demand_of`, but the issue description says `final_demand_of`.

Sorry about that. I meant `demand_of`

> If you wanted to query the amount of energy which enters the converter (from the energy_distribution_coal_gas on the right), you should run supply_of_coal_gas.

I never knew that! Very useful! That solves my issues.
