### ISSUE TITLE
Rails code reloading does not work

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#809]
<img width="518" alt="screen shot 2016-01-18 at 10 10 05 am" src="https://cloud.githubusercontent.com/assets/2676542/12387285/b80a3f10-bdcb-11e5-9435-a1479ca9c6e7.png">

When running et-engine locally this error sometimes flies by in my console. I would have a clue how to approach this error but I hope that you might know directly how to resolve this. If not than I'll be happy to try and fix it.

I tried jumping branches; ie. from `staging` to `master` but that didn't really resolve it. 

```
Etsource is at 0768a45
Etmodel is at b941856
Etengine is at d67fef8
```

After restarting `etengine` locally everything is fine.

**Comment by antw** [comment]
This has been present since ETE was moved to Rails 4; something changed in the Rails development-mode code reloader and this problem has been a problem ever since. :disappointed: 

As far as I can tell, when you make a change to a Ruby file Rails reloads the code, but for some reason there are still old `Input` objects being used to execute queries. My assumption was that this is because `Input` objects [are cached](https://github.com/quintel/etengine/blob/master/app/models/in_memory_record.rb#L41-L46), but removing that caching doesn't solve the problem.

Unfortunately, `Input` isn't the only class which isn't getting reloaded properly; I suggest we take a closer look at this when we upgrade to Rails 5.

**The only known solution is to restart the application.** You can make this a little less painless by building the ETSource data manually, which will reduce the amount of time ETEngine takes to load: in config/config.yml set `etsource_live_reload` and `etsource_lazy_load_dataset` to false, and run `bundle exec rails deploy:calculate_datasets`.

**Comment by grdw** [comment]
@dennisschoenmakers @ChaelKruip can this be fixed with any priority, it's becoming a bit frustrating to have to restart ETEngine everytime I make an edit to ETEngine.. .

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers @ChaelKruip can this be fixed with any priority?

No easy fix present here yet. I guess we could try to migrate to Rails 5, because that is a good idea anyways, right @antw?

**Comment by antw** [comment]
I've pushed a sort-of fix, whereby cached instances of Input and Gquery will be removed when Rails reloads. This prevents the need to restart Rails.

However, it still takes 10+ seconds to fetch all the Inputs and Gqueries from ETSource. Better than it was before, but still not ideal.
