### ISSUE TITLE
Future of GQL not correct for AREA(number_of_residences)

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#810]
This is a follow up from https://github.com/quintel/etmodel/issues/1934

**Comment by grdw** [comment]
Two possible things:

- One it happens when scaling and it's stuck. However this cannot be the problem since I see the value scale in the console.
- Or the gquery responsible for determining the future of `AREA(number_of_residences)` and the gquery-chain behind it doesn't make sense.

Did found [this](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_misc/households_number_of_old_houses.ad) but I can't say if something is wrong with it.

**Comment by grdw** [comment]
Update: credits to @RobTerwel 

If you change the `households_number_of_old_houses` than the future value of your scaled model value for `number_of_residences` will be the `households_number_of_new_houses` + scaled old houses and vice versa.

So if your default slider positions for `households_number_of_old_houses` is 20 and your `households_number_of_new_houses` is 10. And you drag the `households_number_of_old_houses` to 2 than your `number_of_residences` is 12. If you however left `households_number_of_old_houses` unchanged and changed the `households_number_of_new_houses` to 2 than your `number_of_residences` would change to 22.

**Comment by grdw** [comment]
@antw 

Where in the code is [this](https://github.com/quintel/etengine/blob/master/app/models/scenario_scaling.rb#L173-L175) executed? I'm thinking that the problem lies within the fact that when you drag the `households_number_of_new_houses` but don't touch the `households_number_of_old_houses` the slider for `households_number_of_old_houses` doesn't get scaled causing this bug.

**Comment by antw** [comment]
> Where in the code is this executed (somewhere in scenario_merger.rb)?

It's private, and not called within the ScenarioScaler class itself, so I would expect that `input_value` is dead code and can be removed.

The actual scaling of user values [happens here](https://github.com/quintel/etengine/blob/d67fef8bfaa001abde8ad51facf71233e00eb307/app/models/scenario/persistable.rb#L74-L78) – these are the inputs for which the user has provided a value by moving a slider. The min/max/step/default input values [are scaled here](https://github.com/quintel/etengine/blob/d67fef8bfaa001abde8ad51facf71233e00eb307/app/models/input.rb#L441-L454).

Both inputs should be getting scaled:

```ruby
ScenarioScaling.scale_input?(Input.get('households_number_of_old_houses'))
=> true

ScenarioScaling.scale_input?(Input.get('households_number_of_new_houses'))
=> true
```

**Comment by antw** [comment]
I have found the issue; bear with me for a bit and I'll push and explain the fix.

**Comment by grdw** [comment]
@antw Allright! I'm very curious.

**Comment by grdw** [comment]
So it was a caching problem after all. Thanks for the fix!

**Comment by antw** [comment]
Not really a caching problem; more an oversight in not updating all of the `Input` methods to account for the scaling system.

[This line in the Input](https://github.com/quintel/etsource/blob/0768a45d43e2c4f2ef21c7d32768ef7cc3b1e5dd/inputs/demand/households/households_misc/households_number_of_old_houses.ad#L43) was what I noticed. The `number_of_residences` attribute is set by adding the number of old houses with the number of new houses.

However, if the user had not set `number_of_new_houses`,  `INPUT_VALUE(households_number_of_new_houses)` would return an *unscaled* value. This is because it would directly call `Input#start_value_for`. `start_value_for` did not know about the scaling system, so [it was requesting an unscaled value](https://github.com/quintel/etengine/blob/d67fef8bfaa001abde8ad51facf71233e00eb307/app/models/input.rb#L199) (as it always did in the past). I adjusted it to instead ask for a scaled number if the scenario has been scaled.

**Comment by jorisberkhout** [comment]
Nice! Thanks for diving into this issue and solving it, @grwd and @antw !
