### ISSUE TITLE
QUESTION: Do we need to implement physical input and output efficiencies?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#825]
So far, it has not been relevant to distinguish between input and output efficiencies. The only thing that matters has been the efficiency of an energy flow through a converter. If a heater has an efficiency of 80%, the `output.heat` can be set to be 0.8 and all is well.

With P2P, it become relevant to talk about the input (charging) efficiency and the output (discharging) efficiency.

Looking at [the p2p node](https://github.com/quintel/etsource/blob/master/nodes/households/households_flexibility_p2p_electricity.converter.ad), it seems to me that the output efficiency (85%) is intuitively defined by `- output.electricity = 0.85`.
The input efficiency (89%) is defined somewhat less transparently by `~ input.electricity = 1.0 / 0.89`.

@antw I assume this is a way of saying "of every 1 PJ input, only 0.89 PJ makes it into the converter" right?

I feel it would be more transparent/intuitive to be able to define input (charging) efficiency and the output (discharging) efficiencies directly in the node something like this:

```
- input_efficiency.electricity = 0.89
- output_efficiency.electricity = 0.85
```

@antw @jorisberkhout @dennisschoenmakers what do you think?

**Comment by dennisschoenmakers** [comment]
Good point. 

For which other nodes would this be relevant?

**Comment by ChaelKruip** [comment]
> For which other nodes would this be relevant?

Electric vehicles, which are also batteries in a sense. And perhaps pumped storage if we are going to use that at some point. Storage options in short :smile:

**Comment by dennisschoenmakers** [comment]
```
- input_efficiency.electricity = 0.89
- output_efficiency.electricity = 0.85
```

Would we need to update (all) the other nodes accordingly, or would this be optional for only the (few) storage nodes?

**Comment by antw** [comment]
> @antw I assume this is a way of saying "of every 1 PJ input, only 0.89 PJ makes it into the converter" right?

Yes it is.

I agree that `efficiency = 0.89` is easier to understand than `conversion = 1 / 0.89`. It could be especially confusing to newcomers since *output* efficiencies don't need the `1 / x`.

I'm not sure how keen I am on having two separate attributes for describing the same thing, especially since input `conversion` does make sense for most other nodes (where they describe the *share* of input carriers, rather than an efficiency). It *would* be nice to find a way to support both ways of doing things.

I think this was more a workaround for the fact that in ETEngine's model, P2P would be better represented as *two* converters: one for charging, one for discharging.

```
[ Local Elec ] <-elec- [ P2P ] <-elec- [ P2P Input ]
                     /               /
                 loss            loss


P2P Input:
  output.electricity = 0.89
  output.loss = elastic

P2P:
  output.electricity = 0.85
  output.loss = elastic
```

This fits with using *output* to model efficiency (which is what we do everywhere else), but it's pretty cumbersome. Hence the ugly `1 / 0.89` input conversion.

**Comment by ChaelKruip** [comment]
> I'm not sure how keen I am on having two separate attributes for describing the same thing, especially since input conversion does make sense for most other nodes

I agree. 

>  think this was more a workaround for the fact that in ETEngine's model, P2P would be better represented as two converters: one for charging, one for discharging.

I have been thinking along these lines as well. Let's add it to the long list of things we could do with sub-graphs :smiling_imp:

**Comment by dennisschoenmakers** [comment]
> Let's add it to the long list of things we could do with sub-graphs :smiling_imp:

OMG you're so evil :smile:
