### ISSUE TITLE
Input capacity methods return incorrect values for P2P storage techniques

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etengine#829]
### Background

The `input_capacity` of a converter is defined in <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/converter_api/cost.rb#L28-L36"a>cost.rb<a/> as follows:

```
def input_capacity
    fetch(:input_capacity) do
      electric_based_input_capacity ||
        heat_based_input_capacity ||
        cooling_based_input_capacity ||
        typical_input_capacity || 0.0
    end
  end
  unit_for_calculation "input_capacity", 'MWinput'
```

which means (to my understanding) the engine fetches the first of these `input_capacities` it can find or calculate and returns zero otherwise.  The first three (`electric_based_input_capacity`, `heat_based_input_capacity` and `cooling_based_input_capacity`) are methods, the `typical_input_capacity` is specified in ETSource for converters which have an input of a different carrier.

For storage techniques where both the input and output is electricity (P2P) we have defined an `electricity_output_capacity` and `typical_input_capacity` since charging and discharging batteries typically occurs at different speeds. 
### Problem

However, because of this priority listing of input_capacities, the engine first tries to compute the `electricity based_input_capacity` and actually manages because this converter has both an `electricity_output_capacity` and `electricity_output_conversion`:

```
 def electric_based_input_capacity
    fetch(:electric_based_input_capacity) do
      if electricity_output_conversion && electricity_output_conversion > 0
        electricity_output_capacity / electricity_output_conversion
      end
    end
  end
  unit_for_calculation "electric_based_input_capacity", 'MWinput'
```

Therefore, the `typical_input_capacity` we specified for the charging capacity simply gets overruled by the `electric_based_input_capacity`, which has quite a different value (0.00126 MW vs 0.0052 MW, resp.). Querying `V(households_flexibility_p2p_electricity, input_capacity)` returns the incorrect value.

![screen shot 2016-03-22 at 10 10 49](https://cloud.githubusercontent.com/assets/14106387/13946712/6cab2b7e-f016-11e5-9037-5711285b711b.png)
### Possible solutions

Putting the `typical_input_capacity` first in the `input_capacity` definition listing above is probably a way to fix this.

The only converter affected is `households_flexibility_p2p_electricity`, since in electric cars we convert the energy stored into `car.kms`. 

Re-assign at will.

**Comment by ChaelKruip** [comment]
Thanks @RobTerwel for looking into this and your clear account of the situation. I am not yet certain if the above really is a problem because of the following: the P2P node is **not** used by ETEngine in the usual sense. I mean that the node is chiefly a placeholder for cost data but does not participate in the *yearly* energy calculation. This would not make sense because the energy 'demand' of the node is typically zero over the course of the year as it charges roughly as much as it discharges. 

The real question is if Merit (where the hourly calculation is performed) uses the correct capacities and efficiencies. @antw can you answer that question at some point? Lowish priority.

**Comment by ChaelKruip** [comment]
@antw can you have a look at this?
