### ISSUE TITLE
Migrate Ameland and IABR (beta) scenarios to presents in production

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#835]
* Ameland scenario: https://beta-pro.energytransitionmodel.com/scenarios/515530

* AIBR routekaart 2034: http://beta.pro.et-model.com/scenarios/519784

For this we'll need to migrate all the special inputs created by @AlexanderWirtz from ETSource staging to production as well

**Comment by jorisberkhout** [comment]
> For this we'll need to migrate all the special inputs created by @AlexanderWirtz from ETSource staging to production as well

As discussed with @dennisschoenmakers after consulting @RobTerwel , I think it is best if we do a full deploy instead of cherrypicking the 'special inputs' from Beta to Live. Other than these special inputs and the move to `https://` (which has already been deployed to Live), not a lot has happened. This full deploy should **not** include the merit order charts that @grdw is currently creating.

> Migrate Ameland and IABR (beta) scenarios to presents in production

I will create presets and make them available for testing on the Beta server. Once this is done, I will ask you guys to do some testing and ask @grdw to help with the actual deploy.

**Comment by AlexanderWirtz** [comment]
Will need to migrate the GEA scenarios as well. They do not need presets, though, so no extra work

**Comment by jorisberkhout** [comment]
> Will need to migrate the GEA scenarios as well.

Can you give me a pointer to those scenarios, @AlexanderWirtz ?

**Comment by AlexanderWirtz** [comment]
I can, but I can migrate them fine myself, as long as the required etsource commits are deployed to live.

**Comment by jorisberkhout** [comment]
As mentioned by @antw in quintel/etsource#1109 it is not currently possible to create a preset for a scaled scenario. How badly to we want this, @dennisschoenmakers ?

**Comment by AlexanderWirtz** [comment]
For our scales scenarios (GEA and IABR) this is not a must.

**Comment by grdw** [comment]
The production scenarios are:

IABR: https://pro.energytransitionmodel.com/scenarios/291793
Ameland: https://pro.energytransitionmodel.com/scenarios/291787

Both scenarios belong to Alex's user.

**Comment by jorisberkhout** [comment]
The local scenarios are now available on the Live server. Closing this issue
