### ISSUE TITLE
Primary CO2 emission method returns unexpectedly low values in transport with new refinery modelling

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etengine#860]
### Background

On the branch `refineries` I've integrated the production of transport fuels in the industry with the transport sector. The `useful_demand` of `useable_heat` and non-energetic `crude_oil` together are transformed into refinery products in the new node `industry_refinery_transformation_crude_oil`. The refinery products which are transport fuels are then distributed to the transport FD nodes; for every fuel, surplus production is exported and shortages are imported.

### Problem

This implementation works out very well energetically, but it leads to a significant and unexpected reduction in CO2 emissions of the transport sector (that of other sectors is the same, locally and on beta). Emissions drop from 36.8 Mton to 2.6 Mton. Whereas mild changes could be expected as a result of different efficiencies, the extent of this drop seems to be an indication that a calculation method might have trouble dealing with this new modelling. 

The primary_co2_emission` method which calculates these emissions recursively is defined in <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/recursive_factor/primary_co2.rb">primary_co2.rb<a/>. It makes use of the recursive factor defined <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/recursive_factor/base.rb">here<a/>. I dug a bit into this method but its mechanisms are not fully clear to me.

### Noteworthy observations

- On staging the `Energetic CO2 emissions per sector` chart shows us emissions totals of 36.8 Mton in the transport sector. Locally, this amounts to 2.6 Mton. When I manually set refinery size to 0 locally, so that all transport fuels are imported, the CO2 emissions in transport increase to 33 Mton - a value which is much more sensible. This seems to me an indication that the troublesome edges are found between the refinery node `industry_refinery_transformation_crude_oil` and distribution node `energy_distribution_gasoline`.
- Many edges leaving from the refinery are of the `flexible` type, and often `reversed`. The method might have some trouble with these.
- The `primary_demand` of these edges are calculated correctly
- Debugging referred me to the `loss_compensation_factor`

@antw, could you help me uncover what is troubling the `primary_co2_emission` method and responsible for returning these unexpectedly low values in the transport sector?

**Comment by antw** [comment]
I've pushed an ETSource branch with a possible fix; would you mind checking it out and seeing if the results are more in line with expectations?

There were two nodes/converters between `industry_refinery_transformation_crude_oil` and the source of the primary energy which had `free_co2_factor` set to 1.0. That results in all energy passing through those nodes being considered "clean", and having no CO2 emissions.

* **industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic**

  Hopefully changing the CO2 factor on this node is not controversial , since [it was only added on July 19th](https://github.com/quintel/etsource/commit/dcc76f6d3504c1f9b192dcff896adf9cc7d74291).

* **industry_final_demand_crude_oil_non_energetic**

  Changing this node may be more troublesome, since it has had a `free_co2_factor` of 1.0 [since *at least* late-2014](https://github.com/quintel/etsource/commit/f301e5a5). I'd like to hear @ChaelKruip's opinion on this.

**Comment by RobTerwel** [comment]
Thank you, @antw , this fix helped me realise something about the processes we're modelling. I'll dig into this a bit deeper and report back my findings once I have a clearer idea of how to go about this.

**Comment by RobTerwel** [comment]
Alright, here goes:

First of, I realised we probably don't have to change anything in the industry and everything can stay it is the way on the `refineries` branch. The crucial problem here, it seems, is that the primary CO2 emission method does not take into account the actual losses of consuming transport fuels anymore, on this branch. The reason behind it, I think, but please correct me if I'm wrong, is that *the `primary_co2_emission` method returns 0 for any chain/pathway in the graph that somewhere encounters a node with a `free_co2_factor` of 1.0*. 

Thus, the chain of burning fossil fuels made out of non-energetic crude oil takes into account the CO2 emissions of producing the heat necessary for the refineries, but not the actual burning of, say, the diesel in the transport sector. 

This can easily be seen in the following example: in a clean NL scenario the `transport_truck_using_diesel_mix` converts about 180 PJ of diesel into `car_kms` with a 10% efficiency. This means that about 160 PJ is burnt and lost. Diesel having a `co2_conversion_per_mj` of 0.073 kg/MJ, this amounts to 160 PJ * 0.073 Mton/PJ = over 12 Mton of CO2 emissions.  Querying the `primary_co2_emission` of this converter, however, returns 0.8 Mton of CO2 emissions. 

@antw, is my hypothesis that this method only returns non-zero values for chains without nodes with a `free_co2_factor` of 1.0 correct, or is there something else going on? And if so, would it require a lot of effort to rewrite it/make an exception such that these transport fuels do emit CO2 as specified by their carrier's `co2_conversion_per_mj` when used?

**Comment by RobTerwel** [comment]
After discussing with @jorisberkhout , we came up with a more detailed and better explanation of what's going on. When the refineries produce a transport fuel (e.g. diesel), the carrier attributes are determined based on the carriers it originates from. Hence, also the `co2_conversion_per_mj` attribute is determined based on the refinery input. Since about 95% of the fuel input is non-energetic crude oil (with `free_co2_factor`=1.0) and 5% `useable_heat`, their weighted average results in a very low `co2_conversion_per_mj` attribute for the diesel produced in refineries. Diesel that is imported will have the standard and *correct* carrier attributes as specified in <a href="https://github.com/quintel/etsource/blob/master/carriers/diesel.ad#L5">the diesel carrier source analysis<a/>.

Therefore, a fix would consist of giving all output carriers of the `industry_refinery_transformation_crude_oil` node the standard (static) carrier attributes, not newly calculated (dynamic) ones. @antw , would it require a lot of effort to implement such an exemption?

**Comment by antw** [comment]
It's my understanding that the *"primary"* in `primary_co2_emission` means that we're querying the CO2 emissions in producing the *original* source of the energy (in this case, the extraction or import of crude oil), accounting for losses and conversions along the way. Therefore, taking the CO2 per MJ from the diesel carrier isn't the same as the primary CO2 emission, because this energy doesn't enter the graph as diesel.

I need @ChaelKruip to jump in here, because I'm not 100% sure I'm correct. 😬 

If you *really* want to take the CO2 emissions from the diesel carrier, you could do so with a Gquery like this:

```ruby
SUM(V(
  INPUT_SLOTS(V(energy_production_diesel)),
  "external_value * carrier.co2_conversion_per_mj"
))
```

... which translates as: For each input slot on `energy_production_diesel` (there's only one: `diesel`), multiply the energy flowing through the slot (a value in MJ) by the CO2 emissions of the carrier.

**Comment by ChaelKruip** [comment]
@RobTerwel and I have had a couple of insights about this which @RobTerwel will document later.

**Comment by RobTerwel** [comment]
> @RobTerwel and I have had a couple of insights about this which @RobTerwel will document later.

The first few insights have been posted in https://github.com/quintel/etengine/issues/866 . Closing this issue.
