### ISSUE TITLE
Initializer inputs; when should they be applied?

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#895]
@antw We're currently trying to implement the initializer inputs. We're able to set the demand of a certain 'converter' and that seems to work. 

*What I found out technically:*
The `Gql::Gql` object is used when `gql(..)` is called on a `Scenario`. When calling that the first time [?] the datasets are intitialized, the user values applied and the graph is than calculated; much like you specified [here](https://github.com/quintel/atlas/issues/74). [Right now, I'm doing it inbetween step 1 and 2](https://github.com/quintel/etengine/pull/894).

The end-game would be to do it somewhere during step 1 (before the `graph` is cloned). But than again I need the `QueryInterface` to run a serie of Inputs on the graph. So what might be a way to do that? Also should it live inside of `Gql::Gql`? 

I'm trying to validate the idea behind my hacky solution a little bit. 😅

**Comment by antw** [comment]
> I'm trying to validate the idea behind my hacky solution a little bit.

I think the way you're doing it is perfectly fine. Performing the inputs before the graph is cloned probably isn't worth the added complexity.

**Comment by grdw** [comment]
> I think the way you're doing it is perfectly fine. Performing the inputs before the graph is cloned probably isn't worth the added complexity.

That makes sense 👍

**Comment by ploh** [comment]
Reopened because this is not yet clear to me. :blush:

> Edit: Actually, doing it before the clone won't work anyway, since researchers will want to set initializer inputs through ETModel.

The initializer inputs will be set in etsource in derived_dataset.ad files. These could certainly be applied before the clone, could they not?
Another thing is that the researchers will want to quickly see the result of trying some new inputs, but that will be done as it is today, with a scenario's user_values. And once they are satisfied with the outcome, they will copy the user_values into the derived_dataset.ad initializer inputs.

> I think the way you're doing it is perfectly fine. Performing the inputs before the graph is cloned probably isn't worth the added complexity.

1. Do you think it would be very complicated to do this? Do you not just have to create a new (temporary) QueryInterface and apply the inits?
1. Correct me if I am wrong, but the way it is currently done, all the inits are re-computed on every request, right? Or are they somehow intelligently cached?

Excuse me, if I sound a little negative here. I just want to understand and make sure we are all talking about the same things exactly. :slightly_smiling_face:

**Comment by antw** [comment]
> The initializer inputs will be set in etsource in derived_dataset.ad files. These could certainly be applied before the clone, could they not?

The reason I think this won't work is that a user may want to change the value of an initializer input when editing in ETModel. Perhaps you decide that there aren't enough wind turbines in the Ameland dataset, so you might load up a new scenario using the `ameland` dataset, and change the initializer input (with a slider) for wind turbines. When satisfied, I guess you'd copy/paste the updated initializer inputs into the `.ad` file.

If the initializer inputs are applied *before* the clone, there'd be no way to reliably set a different value for the input using ETModel. Most inputs could be applied a second time with the new value (after the clone), but I don't think this is true for all of them. Any input which uses a relative value (`update_type=%` or `update_type=%y`) could almost certainly *not* be applied twice.

Let's imagine there's an init. input to build *a percentage* more turbines (rather than an explicit number):

1. **Base value** (scaled, but before init. inputs): 100 turbines  
    **Dataset init. input value**: 10%
2. **Number of turbines** (scaled, after init. inputs): 110 turbines (100 * 1.1)
3. *[ dataset cloned ]*
4. *[ reapply initializer inputs which have different values in the scenario ]*  
    **User/scenario init. input value**: -15%
5. **Final value**: 93.5 turbines (110 * 0.85) [should be 85! (100 * 0.85)]

This could be solved by not allowing users to edit initializer input values in ETModel, and requiring that changes must always be done via the `.ad` document, but @AlexanderWirtz was understandably [very much against that](https://github.com/quintel/internal/issues/5#issuecomment-266688729).

**Comment by ploh** [comment]
> 5. **Final value**: 93.5 turbines (110 * 0.85) [should be 85! (100 * 0.85)]

With our current (after the clone) implementation for applying the init. inputs the result would also be 93.5.
And maybe that is a good thing... it should be the case that a scenario's user_values are applied _on top_ of the init. inputs rather than _instead_ even if referencing the same input.ad (which should, on the other hand, rarely happen).
For tweaking a derived dataset this might be not ideal, but for using it inside a scenario it is essential: You want the carefully prepared derived dataset as the basis to which your slider settings are applied and not accidentally overwrite the derived dataset data by setting a slider.

My proposition to solve this:
We create an export button for a scenario based on a derived dataset which combines the existing init. inputs of the dataset with the user_values of the scenario and returns updated init. inputs.

**Comment by antw** [comment]
> With our current (after the clone) implementation for applying the init. inputs the result would also be 93.5.

I don't see why? If the visitor provides a different value for the initializer input (-15% instead of +10%), why would the new value not simply overwrite the one defined in the derived region, with the init. input being executed with the new value instead?

> For tweaking a derived dataset this might be not ideal, but for using it inside a scenario it is essential: You want the carefully prepared derived dataset as the basis to which your slider settings are applied and not accidentally overwrite the derived dataset data by setting a slider.

@AlexanderWirtz's point was that he wants sliders in ETModel so that researchers can modify the *initializer* inputs as if they were a "normal" input, while they are constructing their scaled-down regions.

**Comment by ChaelKruip** [comment]
> @AlexanderWirtz's point was that he wants sliders in ETModel so that researchers can modify the initializer inputs as if they were a "normal" input, while they are constructing their scaled-down regions.

Perhaps I'm speaking before my turn here but I think that would be a 3.0 version of the scenario scaling functionality. At the moment (MVP), it is important that the researcher:
* can override default values (from a scaled NL dataset) for demand of nodes etc. in Excel with well documented sources.
* those overrides are communicated to the *present* graph of the local dataset

The user should then be able to make scenario's based on the local present graph/dataset using the ETM interface with sensible slider-caps.

Right @AlexanderWirtz?

**Comment by antw** [comment]
> Perhaps I'm speaking before my turn here but I think that would be a 3.0 version of the scenario scaling functionality.

The impression I got was that so long as init. inputs cannot be easily tweaked in the front end, researchers won't be able to move on from their current technique of using `present` and `both` inputs. Which kinda means that init. inputs in their current form won't be used by anyone? It's probably *me* misunderstanding the priorities, so I'll let @AlexanderWirtz speak for himself. :wink:

Even so, given that this is an eventual goal, I still think it makes sense to execute init. inputs *after* the clone so that we may retain the option of allowing them to be edited in ETModel at a later date.

**Comment by ploh** [comment]
> > With our current (after the clone) implementation for applying the init. inputs the result would also be 93.5.

> I don't see why? If the visitor provides a different value for the initializer input (-15% instead of +10%), why would the new value not simply overwrite the one defined in the derived region, with the init. input being executed with the new value instead?

Because we do that in a new method [`apply_initializer_inputs`](https://github.com/quintel/etengine/pull/894/files#diff-cbbcb93ada622f63d53fa15c3dce452aR337) which is called inside [`init_datasets`](https://github.com/quintel/etengine/pull/894/files#diff-cbbcb93ada622f63d53fa15c3dce452aR245). And this runs [_before_ `update_graphs`](https://github.com/quintel/etengine/pull/894/files#diff-cbbcb93ada622f63d53fa15c3dce452aR212) (in which the user_values are applied).

> @AlexanderWirtz's point was that he wants sliders in ETModel so that researchers can modify the initializer inputs as if they were a "normal" input, while they are constructing their scaled-down regions.

I think more often he wants to put user_values directly in the dabase instead of moving sliders, but the principle is, of course, the same :stuck_out_tongue_winking_eye:
And my proposed "init. inputs + user_values export" would allow that.

> > Perhaps I'm speaking before my turn here but I think that would be a 3.0 version of the scenario scaling functionality.

> The impression I got was that so long as init. inputs cannot be easily tweaked in the front end, researchers won't be able to move on from their current technique of using present and both inputs. Which kinda means that init. inputs in their current form won't be used by anyone?

That was also my impression!

If you start with a freshly created derived dataset (or temporarily comment the init. inputs out in the derived_dataset.ad), you can tweak a scenario with user values and then copy those 1-to-1 into your init. inputs. @AlexanderWirtz was mainly concerned about the initial setup of a derived dataset, right?

**Comment by AlexanderWirtz** [comment]
I am not sure I follow this discussion anymore. @antw I may have said this, but I feel as if the conversation we had about the local datasets solution was quite a while ago and i have no idea wich of the many solutions is actually being implemented. Sorry guys, but I am pretty lost when it comes to this project.

**Comment by ploh** [comment]
> if the user provides a custom value for an *initializer* input, why would we not use that custom initializer value *instead* of the one defined in the derived dataset?

Yes, we would... if the user did provide an *init. input*...

> *(I'm not sure about storing custom init. values in `user_values`, but that's another discussion).*

... but that is exactly the point: The user provides only `user_values`, not _init. inputs_.

Imagine your example with the wind turbines:
The slider for the wind turbines percentage would be set to zero when creating a new scenario based on the derived dataset - it would look very strange if the blank scenario started with anything else.
If the user moves that slider, that should apply _on top_ of the init. inputs that adjusted the wind turbines before.

These examples are a bit theoretical though, since the init. inputs will modify present + future, whereas the sliders only modify future. So in practice it should never be the same input.ad files.

**Comment by ploh** [comment]
> Sorry guys, but I am pretty lost when it comes to this project.
@AlexanderWirtz Let me get you up to speed next week!?
