### ISSUE TITLE
Scaling of derived scenarios

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#902]
Follow up from https://github.com/quintel/etmodel/issues/2328

----

**Use cases:**

*1. Using a derived dataset for a scenario*
1. I select Ameland with a number of residences of 1000. 
2. I drag the `number_of_residences` up to 1200. 
3. My scaling factor should be (1200 / ~7.000.000) = 0.0001714285714 <sup>[1]</sup>

*2. Scaling a derived scenario*

1. I select Ameland with a number of residences of 1000. 
2. I drag the `number_of_residences` up to 1200. 
3. I scale this scenario down to 100
4. My scaling factor should be (100 / 1200) = 0.083333 * [1] <sup>[2]</sup>

*2. Scaling a scaled derived scenario*

1. Perform step 1
2. Scale down to 50 households
3. My scaling factor is (50 / 1200) = ~0.04 * [1] <sup>[3]</sup>

**Comment by grdw** [comment]
@antw Could you shed some light on how this currently works with scaling of a scaled scenario, because on beta etmodel this seems to work great. But with a derived dataset ETModel says no and I don't know why.

**Comment by antw** [comment]
It seems like the re-scaled scenario is using an incorrect base_vaule? It's using the `number_of_residences` from the scaled scenario (100) instead of the original region (1200). The base_value is [set here](https://github.com/quintel/etengine/blob/470256764853fa338a13543e272de324bd46610b/app/controllers/api/v3/scenarios_controller.rb#L95-L101). If the parent scenario has a scaler, the base_value should be re-used; if it doesn't, the number_of_residences of the parent scenario is queried and used as the new base_value (this should be the case when scaling a scenario for the first time).

That sounds suspiciously similar to what is happening here, but doesn't make much sense as I would expect `parent.scaler` to be set [on line 96](https://github.com/quintel/etengine/blob/470256764853fa338a13543e272de324bd46610b/app/controllers/api/v3/scenarios_controller.rb#L96).
