### ISSUE TITLE
Flushing the cache from the command line doesn't seem to work

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#914]
Last friday @AlexanderWirtz experienced a problem with his scenario on the beta server. It turns out there was some stale cache with the wrong `ndp` key instead of `noorderplatsoenbuurt` key. 

I managed to find that out by performing this task from the command line:

```bash
echo "stats cachedump x 0" | nc localhost 11211

# Where x is a positive integer between 1 and Infinity
```

When I performed:

```bash
echo "flush_all" | nc localhost 11211
```

The above `stats cachedump ... ` command still showed the old cache 🤔 

How can this be? 

Am I using the wrong command to read the cache or?

**Comment by grdw** [comment]
To add to this: I can't see the old cache anymore (with the `ndp`) but I could last friday.

**Comment by dennisschoenmakers** [comment]
```
NoMethodError (undefined method `analysis_year' for nil:NilClass):
  app/models/setting.rb:97:in `start_year'
  app/models/setting.rb:149:in `public_send'
  app/models/setting.rb:149:in `block in to_hash'
  app/models/setting.rb:148:in `each'
  app/models/setting.rb:148:in `each_with_object'
  app/models/setting.rb:148:in `to_hash'

**Comment by dennisschoenmakers** [comment]
Well, I think this isn't the problem, opening a new Issue

**Comment by grdw** [comment]
It might still be a problem but I think it's unrelated to @AlexanderWirtz problems.

**Comment by antw** [comment]
> How can this be?

I'm fairly certain a list of available datasets is being retained in memory by the Ruby process somewhere (e.g. `@datasets ||= ...`), which is why it takes a restart of ETEngine for new datasets – or renamed datasets in this instance – to load. However, I can't find any obvious sign of that being the case.

Importing a new version of ETSource [is supposed to clear both the in-memory and memcached caches](https://github.com/quintel/etengine/blob/8a32f96a02a494cf10259c499aabdcc144fdbfdd/app/models/nasty_cache.rb#L80-L81) (but obviously cannot do anything about a value wrongly stored as a class or class-instance variable). This is the first I've heard of memcache having stale values; it's conceivable that memcached *was* cleared and then re-populated with a stale value.

**Comment by grdw** [comment]
>  it's conceivable that memcached was cleared and then re-populated with a stale value.

Hmmm 🤔 

> Importing a new version of ETSource is supposed to clear both the in-memory and memcached caches

This is weird. @DorinevanderVlies just imported a new version of ETSource (with a new dataset). However the cache was still present after manually doing a:

` bundle exec cap staging memcached:flush` 

The new dataset became visible. This was also the case for Noorderplatsoen.
