### ISSUE TITLE
Use the dataset id as the 'area' attribute instead of the 'area' for a scenario

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#915]
This is to make renaming of a dataset easier.

**Comment by antw** [comment]
I disagree with this insofar as the ID is a deprecated field and a remnant from the days before we had (modern) ETSource and Atlas. We left the `id` and `area` fields there because we weren't sure if any existing code depended on them, but the intention was for the area `key` to be the replacement (which is defined by the filename of the dataset) since it has the property of being human-readable and enforced uniqueness by Atlas.

Personally, I think renaming a dataset is exceedingly rare – it happened once in five years – it's not too much trouble for us to write a migration; whereas manually incrementing ID fields in `.ad` files *is* going to get forgotten one day. 😆

**Comment by grdw** [comment]
> I think renaming a dataset is exceedingly rare – it happened once in five years 

Well, I think that's going to change. I had to rename a dataset this friday. Also, I probably have to rename a dataset within the next two weeks. So I think it's going to happen quiet often with local datasets at least. And obviously this should be prevented.

The id field might be deprecated but maybe it should be possible to rename a dataset with the `area` attribute 🤔 . So id est, use the `area` attribute as a label for the front-end of ETModel (because that's the only thing people care about) - we could also just use a translation key in my opinion.

The name of a dataset however should not be changeable. Maybe we could infer some rules on how to create a name for a dataset .. for instance ([ISO code of the province of The Netherlands](https://nl.wikipedia.org/wiki/ISO_3166-2:NL) + name of the city / street. `nl-dr` as Drenthe and `nl-dr-assen` (as Assen). I'm not sure if this is a nice approach but what would be desirable is that the names of the folder and the names of the `.ad` file **do not change**.
