### ISSUE TITLE
has_industry, has_agriculture, has_other flags should not only disable parts of the interface in etmodel but should also exclude these sectors from the graph calculation.

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#916]
When setting the `has_industry`-flag to `false` in a local dataset it is still necesarry to set all demands to 0 for industry with initializer inputs. This seems a little redundant.

**Comment by antw** [comment]
> See title.

Can you clarify what you mean by "exclude [...] from the graph calculation"? 😆 

[The DisableSectors plugin](https://github.com/quintel/etengine/blob/8a32f96a02a494cf10259c499aabdcc144fdbfdd/app/models/qernel/plugins/disable_sectors.rb) does this already by setting the demands of a disabled sector to zero. Nodes in these sectors will not be calculated since their demand has been set explicitly.

**Comment by grdw** [comment]
@antw I updated the description.
