### ISSUE TITLE
Primary demand method does not know how to deal with converter efficiencies > 100%

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etengine#936]
As described in https://github.com/quintel/etengine/issues/929#issuecomment-321262448, there are differences between the primary demands of all converters in the useful demand group and the final demand group for most sectors.

I have traced down the cause of the differences in the households and buildings sector. The are entirely caused by the fact that the efficiencies of `households_space_heater_combined_network_gas` and  `buildings_space_heater_network_gas` are higher than `100%` , namely `106.7%` (arghh, not again!).

As described in the aforementioned comment, for households, the primary demand of useful demand is `16,... PJ` higher than the primary demand of final demand. This value is exactly 6.7% of the primary demand for natural gas of `households_space_heater_combined_network_gas`. I can provide a more detailed analysis if required.

It appears to me like the recursive primary demand method does not take the efficiency `> 100%` into account and therefore overestimates the primary demand (for natural gas) of the two converters with these efficiencies.

@antw, do you see an easy fix for this? If not, let's not spend time on solving this, as there might be other solutions (like getting rid of efficiencies `> 100%`.

**Comment by jorisberkhout** [comment]
This very same issue causes the entire difference between primary of useful and primary of final in the transport sector as most (or all?) car technologies have "efficiencies" `>100%`.

**Comment by michieldenhaan** [comment]
I've added the priority label because this no longer affects nodes 'to the left' of final demand. The heat network has a few burners with >100% efficiencies. As a result, when querying the primary demand of the final demand steam hot water nodes the resulting number is too high.

I've created a scenario to illustrate this (BETA: 1406508). In this scenario, gas is only used for 1 purpose: to generate heat for the `households_final_demand_steam_hot_water` node using the `energy_heat_backup_burner_network_gas` burner. This burner has a 103% efficiency.

Going right to left in the graph:

Total primary natural gas import in this scenario is 2.49 PJ.
![image](https://user-images.githubusercontent.com/32056448/108742041-99dd4b80-7537-11eb-9e61-afe40b9de7a5.png)

Of this, 2.45 PJ 'makes' it to the gas network node (due to losses):
![image](https://user-images.githubusercontent.com/32056448/108742124-afeb0c00-7537-11eb-904a-610906a17b87.png)

Of that, 2.44 PJ ends up in `energy_heat_backup_burner_network_gas` node, producing 2.51 PJ heat.
![image](https://user-images.githubusercontent.com/32056448/108742204-c4c79f80-7537-11eb-8722-42068d100793.png)

However, when querying the `primary_demand_of_natural_gas` it returns 2.56 PJ.

![image](https://user-images.githubusercontent.com/32056448/108742745-533c2100-7538-11eb-9f11-af1e80b064d9.png)

This obviously isn't correct as only 2.49 PJ gas is imported/extracted in this scenario.

What seems to be happening:
2.51 heat demand / 0.996 (0.4% loss of `energy_national_gas_network_natural_gas`) / 0.986 (1.4% loss of `energy_treatment_natural_gas`) = 2.56 PJ (i.e. 1.03 efficiency of the burner is ignored).

What should be happening:
2.51 heat demand / 1.03 (burner efficiency) / 0.996 (0.4% loss of `energy_national_gas_network_natural_gas`) / 0.986 (1.4% loss of `energy_treatment_natural_gas`) = 2.49 PJ

Notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
Nice catch @michieldenhaan. @antw is this something that you can look into in the next (or current!) sprint?

**Comment by antw** [comment]
> This burner has a 103% efficiency.

The solution seems to be that we, when calculating with recursive factor, we should cap output conversions (efficiency) to 1.0 (100%). That seems to have the desired effect:

```ruby
future:V(households_final_demand_steam_hot_water, primary_demand_of_natural_gas)
# => 2,486,246,109.3319864

future:V(energy_import_natural_gas, primary_demand_of_natural_gas)
# => 2,486,246,109.331992
```

Is this true for _all_ recursive factor calculations, or just primary demand?

It seems to me that we should *always* cap output shares to 1.0 for recursive factor. In the same scenario I would expect the `primary_co2_emission` of the households node to exactly match that of the natural gas import node, but that isn't currently the case on beta.

| Server | households_final_demand_steam_hot_water | energy_import_natural_gas |
| :-- | --: | --: |
| Beta, not fixed | 144,687,092.33257496 | 140,472,905.17725757 |
| Local, fixed | 140,472,905.17725727 | 140,472,905.17725727 |

**Comment by michieldenhaan** [comment]
Thanks for looking into this! I'm a little bit confused because in my calculation above it looks like we already cap the efficiency at 1.0 while we shouldn't. I.e. if we don't divide by 1.03 (= capping at 1?) the number we arrive at is too high (2.56 PJ). If we do divide by 1.03 we arrive at the correct 2.49 PJ? Your table does look reassuring tho..

> Is this true for all recursive factor calculations, or just primary demand?
Yes, this should be the case for all calculations!

**Comment by ChaelKruip** [comment]
> Thanks for looking into this! I'm a little bit confused because in my calculation above it looks like we already cap the efficiency at 1.0 while we shouldn't. I.e. if we don't divide by 1.03 (= capping at 1?) the number we arrive at is too high (2.56 PJ). If we do divide by 1.03 we arrive at the correct 2.49 PJ? Your table does look reassuring tho..

I have the same confusion. It seems that the efficiency is multiplied by, instead of divided by but if this were the case, that would also mess up all recursive calculations with efficiencies < 1 which seem to be working just fine...

I would be more at ease if I understood why capping the efficiency actually works in solving this issue. Just to make sure that we are not making two mistakes that cancel each other out or anything like that!
Having said that it's reassuring that there seems to be a quick fix at hand 😅

**Comment by antw** [comment]
> I have the same confusion.

The answer *is* pretty confusing, but I also explained my solution incorrectly. I find recursive factor to be really unintuitive. 😞 

We've got two recursive factor methods in ETEngine:

* `recursive_factor` (with losses)
* `recursive_factor_without_losses`

The "with losses" version compensates for loss – as we have been discussing in #1147 – while the "without losses" version does not (this is useful for calculating shares, such as `sustainability_share` and `weighted_carrier_*`).

The "without losses" version works much as you'd expect: inspecting slot conversions and edge shares along the way. The "with losses" version does not, and uses its own approach for calculating shares. Why? I honestly couldn't tell you.

Even looking at the code, I'm struggling to explain why the "with losses" version does its own thing, except that it seems to allow us to ignore edges which carry loss.

Instead of using edge/slot shares, it calculates the child share of the edge manually by running `edge.demand / node.demand` to get a value which combines both the child share and input slot conversion. It calls this the "demanding share".

Demands are in 🔵 blue, slot conversions are in 🟢 green.

### Example one: a simple path

Energy moves from right to left. All shares and slot conversions are 1.0.

![IMG_3981A83D76EC-1 2](https://user-images.githubusercontent.com/4383/108905852-1d6e6980-7618-11eb-92a8-6a3ea3f6eda5.jpeg)

Calculating something recursively on [L] which terminates on [R] (for example, calling `primary_demand` on [L] where  [R] is a primary_energy_demand node) gives a recursive factor of: 1.0 × 1.0 = **1.0**.

Then we multiply the demand of [L] by this recursive factor to get the final value: 100 × 1.0 = **100**. [L] has primary demand of 100.

> ![IMG_0D04F44BDCAF-1](https://user-images.githubusercontent.com/4383/108908846-b81c7780-761b-11eb-84cf-269175afaa1f.jpeg)

### Example two: Input conversion

The same as example one, only [L] now has two input carriers each with an input conversion of 0.5.

![IMG_C09AEC999F94-1](https://user-images.githubusercontent.com/4383/108914022-b1453300-7622-11eb-928c-4bd3857ffd20.jpeg)

The recursive factor of this path is 0.5 × 1.0 = **0.5**. The primary demand will be 200 × 0.5 = **100**. This is correct; all of the primary energy from [R] ends on on [L].

### Example three: Edge child shares

The same as example one, only the middle node [M] now has two outgoing edges: each one carries 50 energy, with only 50 arriving at the [L] node.

![IMG_54071BD48562-1](https://user-images.githubusercontent.com/4383/108906786-2f044100-7619-11eb-820a-1d09b7a22d76.jpeg)

![IMG_3E3779352302-1](https://user-images.githubusercontent.com/4383/108914137-d5a10f80-7622-11eb-93c8-5ba228cf31b2.jpeg)


The demanding shares are both 1.0, so the recursive factor is again 1.0.

Multiply the demand of [L] by this recursive factor to get the final value: 50 × 1.0 = **100**. [L] has primary demand of **50**. This is correct: 50 of the energy from [R] ends up on [L]; the other 50 ends up somewhere else.

### Example four: Output conversions

Exactly the same as example three, only now the two edges which leave [M] are different carriers. The output slot shares are 0.5.

![IMG_AC48110E33AC-1](https://user-images.githubusercontent.com/4383/108914345-1731ba80-7623-11eb-9f24-40a361cee06d.jpeg)

The result is the same as example three: 50 × 1.0 = **50** primary demand.

### Example five: The issue!

Finally we get to the issue! [M] now has an output efficiency of 200%. 100 energy enters, 200 leaves.

![IMG_CD7253FCDB4C-1](https://user-images.githubusercontent.com/4383/108914507-595afc00-7623-11eb-8f6f-54a4b3c6c8b2.jpeg)

Once again, the recursive factor is calculated as 1.0. However, calculating the primary demand reveals that this is obviously not correct: 200 × 1.0 = 200. The primary demand of [L] *should* be 100; the recursive factor should be 0.5.

### My suggestion

What I'm suggesting is not in fact capping the output conversion to 1.0, but adjusting the demanding share when the output conversion is greater than 1.0.

![IMG_557600739E48-1](https://user-images.githubusercontent.com/4383/108909355-5b6d8c80-761c-11eb-9b54-11288da36b77.jpeg)

Now the recursive factor looks like we'd expect: 0.5 × 1.0 = **0.5**. The primary demand of [L] is also correct: 200 × 0.5 = **100**.

### WTF?

To be honest, I don't know why the "with losses" recursive factor does this stuff with demanding share. I'm struggling to make sense of it, as it seem a really obtuse way to calculate information the graph already gives you.

However, when I encounter something like this my reaction isn't "this is stupid, let's rewrite!" but rather the original author probably had *some* reason for doing this that isn't obvious to me ten years later (this code was added in a7b139e: the very first commit to ETEngine after it was extracted out from ETModel). Unfortunately recursive factor has such terrible test coverage that I don't feel confident refactoring it into something that makes more sense _to me_.

This fix does the trick, even though it does nothing to help improve the understandability of recursive factor itself. I'm not convinced this is the best fix possible, but that would require us to have much better test coverage of recursive factor first. 

**You may try it for yourself on the [issues/936 branch](https://github.com/quintel/etengine/tree/issues/936).** I added some tests to assert we get the expected results for `primary_demand`, `primary_co2_emission`, and `primary_demand_of_sustainable` which use `recursive_factor` (with losses), and `sustainability_factory` which uses `recursive_factor_without_losses` (and seems to be unaffected by the original bug).

**Comment by michieldenhaan** [comment]
Thanks @antw! That helps a lot.

I've tested the branch for the above scenario and for a blank NL scenario and both add up perfectly now. I'm happy to go ahead with his. Do you agree @ChaelKruip?

**Comment by ChaelKruip** [comment]
> Thanks @antw! That helps a lot.

It does indeed. Thanks!

> However, when I encounter something like this my reaction isn't "this is stupid, let's rewrite!" but rather the original author probably had some reason for doing this that isn't obvious to me

I commend your compassion for your colleagues @antw! Having said that, I would like to mark this down as a part of the code to be refactored soon. It is quite central to the ETM and I would sleep better if I could actually explain how it worked more easily. 

> I've tested the branch for the above scenario and for a blank NL scenario and both add up perfectly now. I'm happy to go ahead with this. Do you agree @ChaelKruip?

Yes!
