### ISSUE TITLE
Number of units of households_water_heater_network_gas is not set correctly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#944]
Setting its share to 100%, set the number of units to zero!

@antw I realised that this technology is an exception as it is used to balance the group and has an empty update statement:

https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_hot_water/households_water_heater_network_gas_share.ad#L1

**Comment by antw** [comment]
whaaaaat. 😐

All the heat producers are `demand_driven`, so with a share of 100% it should have 7.5M units installed in NL. Although it it connected to the useful demand node with a `flexible` instead of `share` edge, that really shouldn't matter (ETE still calculated the share correctly).

Looking into this...

**Comment by ChaelKruip** [comment]
Very weird indeed. The Mechanical Turk fails about this converter only.
