### ISSUE TITLE
environment_water_water should adapt its demand

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#954]
In [this scenario](https://beta-pro.energytransitionmodel.com/scenarios/743161) (and possible others) the environment_water_water does not update its demand correctly:
<img width="969" alt="cursor_and_energytransitionmodel" src="https://user-images.githubusercontent.com/1303760/31383885-fdf72442-adbc-11e7-86d3-668e52dbbb16.png">

**Comment by antw** [comment]
This is because two industry converters are connected to `environment_water_water` via an `ambient_heat` carrier whose conversion is always 0.0. @ChaelKruip suspects that these industry converters should in fact have been connected to `environment_earth_ambient_heat`.

![screen shot 2017-10-10 at 12 31 13](https://user-images.githubusercontent.com/4383/31384446-f727f0de-adb6-11e7-98ba-3f7235ce68e4.png)

Reassigning as suggested.
